const categories = {
    "Geography": [
        { word: "Mountain", difficulty: "easy" },
        { word: "River", difficulty: "easy" },
        { word: "Ocean", difficulty: "easy" },
        { word: "Desert", difficulty: "easy" },
        { word: "Valley", difficulty: "easy" },
        { word: "Island", difficulty: "easy" },
        { word: "Volcano", difficulty: "easy" },
        { word: "Peninsula", difficulty: "easy" },
        { word: "Plateau", difficulty: "easy" },
        { word: "Glacier", difficulty: "easy" },
        { word: "Equator", difficulty: "hard" },
        { word: "Prime Meridian", difficulty: "hard" },
        { word: "International Date Line", difficulty: "hard" },
        { word: "Tropic of Cancer", difficulty: "hard" },
        { word: "Tropic of Capricorn", difficulty: "hard" },
        { word: "Isthmus", difficulty: "hard" },
        { word: "Archipelago", difficulty: "hard" },
        { word: "Delta", difficulty: "hard" },
        { word: "Estuary", difficulty: "hard" },
        { word: "Atoll", difficulty: "hard" },
        { word: "Paris", difficulty: "easy" },
        { word: "Great Wall of China", difficulty: "medium" },
        { word: "Brazil", difficulty: "easy" },
        { word: "Africa", difficulty: "easy" },
        { word: "Statue of Liberty", difficulty: "medium" },
        { word: "Nile River", difficulty: "medium" },
        { word: "Lake Victoria", difficulty: "medium" },
        { word: "Mount Everest", difficulty: "medium" },
        { word: "New York City", difficulty: "medium" },
        { word: "Colosseum", difficulty: "medium" },
        { word: "Japan", difficulty: "easy" },
        { word: "Europe", difficulty: "medium" },
        { word: "Eiffel Tower", difficulty: "medium" },
        { word: "Amazon River", difficulty: "medium" },
        { word: "Lake Baikal", difficulty: "medium" },
        { word: "Matterhorn", difficulty: "medium" },
        { word: "China", difficulty: "easy" },
        { word: "Asia", difficulty: "medium" },
        { word: "Golden Gate Bridge", difficulty: "medium" },
        { word: "Mississippi River", difficulty: "medium" },
        { word: "Lake Superior", difficulty: "medium" },
        { word: "K2", difficulty: "medium" },
        { word: "Danube River", difficulty: "medium" },
        { word: "Lake Titicaca", difficulty: "medium" },
        { word: "Kilimanjaro", difficulty: "medium" },
        { word: "Sydney Opera House", difficulty: "medium" },
        { word: "Colorado River", difficulty: "medium" },
        { word: "Lake Tahoe", difficulty: "medium" },
        { word: "Mont Blanc", difficulty: "medium" },
        { word: "Lake Ontario", difficulty: "medium" },
        { word: "Yangtze River", difficulty: "medium" },
        { word: "Mount Kilimanjaro", difficulty: "medium" },
        { word: "Mount Vesuvius", difficulty: "medium" },
        { word: "Great Barrier Reef", difficulty: "medium" },
        { word: "Machu Picchu", difficulty: "medium" },
        { word: "Neuschwanstein Castle", difficulty: "medium" },
        { word: "Gobi Desert", difficulty: "medium" },
        { word: "Burj Khalifa", difficulty: "medium" },
        { word: "Volga River", difficulty: "medium" },
        { word: "Lake Michigan", difficulty: "medium" },
        { word: "Ben Nevis", difficulty: "medium" },
        { word: "Mount St. Helens", difficulty: "medium" },
        { word: "Skellig Michael", difficulty: "medium" },
        { word: "Ganges River", difficulty: "medium" },
        { word: "Lake Champlain", difficulty: "medium" },
        { word: "Petra", difficulty: "medium" },
        { word: "Mount McKinley", difficulty: "medium" },
        { word: "Emerald Isle", difficulty: "medium" },
        { word: "Niagara Falls", difficulty: "medium" },
        { word: "Isle Royale", difficulty: "medium" },
        { word: "Denver", difficulty: "medium" },
        { word: "Mauna Kea", difficulty: "medium" },
        { word: "Forbidden City", difficulty: "medium" },
        { word: "Thames River", difficulty: "medium" },
        { word: "Lake Powell", difficulty: "medium" },
        { word: "Atlantis", difficulty: "medium" },
        { word: "Paris", difficulty: "easy" },
        { word: "Great Wall of China", difficulty: "hard" },
        { word: "Nile River", difficulty: "hard" },
        { word: "Amazon River", difficulty: "hard" },
        { word: "Mount Everest", difficulty: "hard" }
    ],
    "Hollywood": [
        { word: "Actor", difficulty: "easy" },
        { word: "Director", difficulty: "easy" },
        { word: "Oscar", difficulty: "easy" },
        { word: "Red carpet", difficulty: "easy" },
        { word: "Blockbuster", difficulty: "easy" },
        { word: "Movie", difficulty: "easy" },
        { word: "Premiere", difficulty: "easy" },
        { word: "Screenwriter", difficulty: "easy" },
        { word: "Studio", difficulty: "easy" },
        { word: "Sequel", difficulty: "easy" },
        { word: "Cinematography", difficulty: "hard" },
        { word: "Method acting", difficulty: "hard" },
        { word: "Film noir", difficulty: "hard" },
        { word: "Biopic", difficulty: "hard" },
        { word: "Cameo", difficulty: "hard" },
        { word: "Auteur", difficulty: "hard" },
        { word: "Casting couch", difficulty: "hard" },
        { word: "Stunt double", difficulty: "hard" },
        { word: "Box office", difficulty: "hard" },
        { word: "Green screen", difficulty: "hard" }
    ],
    "Cars": [
        { word: "Sedan", difficulty: "easy" },
        { word: "Convertible", difficulty: "easy" },
        { word: "SUV", difficulty: "easy" },
        { word: "Coupe", difficulty: "easy" },
        { word: "Hatchback", difficulty: "easy" },
        { word: "Engine", difficulty: "easy" },
        { word: "Transmission", difficulty: "easy" },
        { word: "Headlights", difficulty: "easy" },
        { word: "Wheels", difficulty: "easy" },
        { word: "Steering wheel", difficulty: "easy" },
        { word: "Differential", difficulty: "hard" },
        { word: "Carburetor", difficulty: "hard" },
        { word: "Catalytic converter", difficulty: "hard" },
        { word: "Torque", difficulty: "hard" },
        { word: "RPM", difficulty: "hard" },
        { word: "Drivetrain", difficulty: "hard" },
        { word: "Suspension", difficulty: "hard" },
        { word: "Chassis", difficulty: "hard" },
        { word: "Fuel injection", difficulty: "hard" },
        { word: "Turbocharger", difficulty: "hard" }
    ],
    "Sports": [
        { word: "Basketball", difficulty: "easy" },
        { word: "Tennis", difficulty: "easy" },
        { word: "Baseball", difficulty: "easy" },
        { word: "Football", difficulty: "easy" },
        { word: "Swimming", difficulty: "easy" },
        { word: "Cycling", difficulty: "easy" },
        { word: "Running", difficulty: "easy" },
        { word: "Skiing", difficulty: "easy" },
        { word: "Golf", difficulty: "easy" },
        { word: "Boxing", difficulty: "easy" },
        { word: "Decathlon", difficulty: "hard" },
        { word: "Biathlon", difficulty: "hard" },
        { word: "Polo", difficulty: "hard" },
        { word: "The Olympic Games", difficulty: "hard" },
        { word: "Bobsledding", difficulty: "hard" },
        { word: "Windsurfing", difficulty: "hard" },
        { word: "Triathlon", difficulty: "hard" },
        { word: "Badminton", difficulty: "hard" },
        { word: "Fencing", difficulty: "hard" },
        { word: "Lacrosse", difficulty: "hard" }
    ],
    "Soccer": [
        { word: "Goal", difficulty: "easy" },
        { word: "Penalty", difficulty: "easy" },
        { word: "Offside", difficulty: "easy" },
        { word: "Corner kick", difficulty: "easy" },
        { word: "Red card", difficulty: "easy" },
        { word: "Yellow card", difficulty: "easy" },
        { word: "Free kick", difficulty: "easy" },
        { word: "Goalkeeper", difficulty: "easy" },
        { word: "Striker", difficulty: "easy" },
        { word: "Midfielder", difficulty: "easy" },
        { word: "Hat-trick", difficulty: "hard" },
        { word: "Nutmeg", difficulty: "hard" },
        { word: "Tiki-taka", difficulty: "hard" },
        { word: "False nine", difficulty: "hard" },
        { word: "Sweeper", difficulty: "hard" },
        { word: "Counter-attack", difficulty: "hard" },
        { word: "Libero", difficulty: "hard" },
        { word: "Man marking", difficulty: "hard" },
        { word: "Zonal marking", difficulty: "hard" },
        { word: "Through ball", difficulty: "hard" }
    ],
    "Animals": [
        { word: "Cat", difficulty: "easy" },
        { word: "Dog", difficulty: "easy" },
        { word: "Elephant", difficulty: "easy" },
        { word: "Lion", difficulty: "easy" },
        { word: "Tiger", difficulty: "easy" },
        { word: "Giraffe", difficulty: "easy" },
        { word: "Kangaroo", difficulty: "easy" },
        { word: "Penguin", difficulty: "easy" },
        { word: "Dolphin", difficulty: "easy" },
        { word: "Shark", difficulty: "easy" },
        { word: "Axolotl", difficulty: "hard" },
        { word: "Platypus", difficulty: "hard" },
        { word: "Tasmanian Devil", difficulty: "hard" },
        { word: "Electric Eel", difficulty: "hard" },
        { word: "Narwhal", difficulty: "hard" },
        { word: "Komodo Dragon", difficulty: "hard" },
        { word: "Emperor Penguin", difficulty: "hard" },
        { word: "Snow Leopard", difficulty: "hard" },
        { word: "Great White Shark", difficulty: "hard" },
        { word: "African Grey Parrot", difficulty: "hard" }
    ],
    "Famous Landmarks": [
        { word: "Eiffel Tower", difficulty: "easy" },
        { word: "Great Wall of China", difficulty: "easy" },
        { word: "Statue of Liberty", difficulty: "easy" },
        { word: "Big Ben", difficulty: "easy" },
        { word: "Colosseum", difficulty: "easy" },
        { word: "Pyramids of Giza", difficulty: "easy" },
        { word: "Machu Picchu", difficulty: "easy" },
        { word: "Taj Mahal", difficulty: "easy" },
        { word: "Sydney Opera House", difficulty: "easy" },
        { word: "Mount Rushmore", difficulty: "easy" },
        { word: "Christ the Redeemer", difficulty: "hard" },
        { word: "Golden Gate Bridge", difficulty: "hard" },
        { word: "Stonehenge", difficulty: "hard" },
        { word: "Neuschwanstein Castle", difficulty: "hard" },
        { word: "Leaning Tower of Pisa", difficulty: "hard" },
        { word: "Angkor Wat", difficulty: "hard" },
        { word: "Chichen Itza", difficulty: "hard" },
        { word: "Sagrada Familia", difficulty: "hard" },
        { word: "Burj Khalifa", difficulty: "hard" },
        { word: "Alhambra Palace", difficulty: "hard" }
    ],
    "Celebrities": [
        { word: "Brad Pitt", difficulty: "easy" },
        { word: "Angelina Jolie", difficulty: "easy" },
        { word: "Tom Cruise", difficulty: "easy" },
        { word: "Jennifer Aniston", difficulty: "easy" },
        { word: "Leonardo DiCaprio", difficulty: "easy" },
        { word: "Taylor Swift", difficulty: "easy" },
        { word: "Beyoncé", difficulty: "easy" },
        { word: "Dwayne Johnson", difficulty: "easy" },
        { word: "Robert Downey Jr.", difficulty: "easy" },
        { word: "Scarlett Johansson", difficulty: "easy" },
        { word: "Benedict Cumberbatch", difficulty: "hard" },
        { word: "Keanu Reeves", difficulty: "hard" },
        { word: "Natalie Portman", difficulty: "hard" },
        { word: "Joaquin Phoenix", difficulty: "hard" },
        { word: "Charlize Theron", difficulty: "hard" },
        { word: "Michael Fassbender", difficulty: "hard" },
        { word: "Cate Blanchett", difficulty: "hard" },
        { word: "Tilda Swinton", difficulty: "hard" },
        { word: "Christoph Waltz", difficulty: "hard" },
        { word: "Saoirse Ronan", difficulty: "hard" }
    ],
    "Food & Drinks": [
        { word: "Pizza", difficulty: "easy" },
        { word: "Burger", difficulty: "easy" },
        { word: "Pasta", difficulty: "easy" },
        { word: "Sushi", difficulty: "easy" },
        { word: "Ice cream", difficulty: "easy" },
        { word: "Salad", difficulty: "easy" },
        { word: "Sandwich", difficulty: "easy" },
        { word: "Steak", difficulty: "easy" },
        { word: "Coffee", difficulty: "easy" },
        { word: "Tea", difficulty: "easy" },
        { word: "Eggs Benedict", difficulty: "hard" },
        { word: "Beef Wellington", difficulty: "hard" },
        { word: "Lobster Bisque", difficulty: "hard" },
        { word: "Croque Monsieur", difficulty: "hard" },
        { word: "Chicken Parmesan", difficulty: "hard" },
        { word: "Tiramisu", difficulty: "hard" },
        { word: "Coq au Vin", difficulty: "hard" },
        { word: "Crème Brûlée", difficulty: "hard" },
        { word: "Spaghetti Carbonara", difficulty: "hard" },
        { word: "Banoffee Pie", difficulty: "hard" }
    ],
    "Books & Authors": [
        { word: "Harry Potter", difficulty: "easy" },
        { word: "The Great Gatsby", difficulty: "easy" },
        { word: "To Kill a Mockingbird", difficulty: "easy" },
        { word: "1984", difficulty: "easy" },
        { word: "The Hobbit", difficulty: "easy" },
        { word: "Pride and Prejudice", difficulty: "easy" },
        { word: "Moby Dick", difficulty: "easy" },
        { word: "The Catcher in the Rye", difficulty: "easy" },
        { word: "The Da Vinci Code", difficulty: "easy" },
        { word: "Lord of the Rings", difficulty: "easy" },
        { word: "War and Peace", difficulty: "hard" },
        { word: "Crime and Punishment", difficulty: "hard" },
        { word: "One Hundred Years of Solitude", difficulty: "hard" },
        { word: "The Brothers Karamazov", difficulty: "hard" },
        { word: "The Grapes of Wrath", difficulty: "hard" },
        { word: "Love in the Time of Cholera", difficulty: "hard" },
        { word: "A Tale of Two Cities", difficulty: "hard" },
        { word: "The Picture of Dorian Gray", difficulty: "hard" },
        { word: "Midnight's Children", difficulty: "hard" },
        { word: "Infinite Jest", difficulty: "hard" }
    ],
    "Historical Events": [
        { word: "World War I", difficulty: "easy" },
        { word: "World War II", difficulty: "easy" },
        { word: "Moon Landing", difficulty: "easy" },
        { word: "American Revolution", difficulty: "easy" },
        { word: "French Revolution", difficulty: "easy" },
        { word: "Industrial Revolution", difficulty: "easy" },
        { word: "Civil Rights Movement", difficulty: "easy" },
        { word: "Fall of Berlin Wall", difficulty: "easy" },
        { word: "Renaissance", difficulty: "easy" },
        { word: "Great Depression", difficulty: "easy" },
        { word: "Signing of the Magna Carta", difficulty: "hard" },
        { word: "Battle of Hastings", difficulty: "hard" },
        { word: "Cuban Missile Crisis", difficulty: "hard" },
        { word: "Boston Tea Party", difficulty: "hard" },
        { word: "Spanish Inquisition", difficulty: "hard" },
        { word: "Storming of the Bastille", difficulty: "hard" },
        { word: "Salem Witch Trials", difficulty: "hard" },
        { word: "Treaty of Versailles", difficulty: "hard" },
        { word: "Fall of Constantinople", difficulty: "hard" },
        { word: "Berlin Airlift", difficulty: "hard" }
    ],
    "Music & Bands": [
        { word: "The Beatles", difficulty: "easy" },
        { word: "Michael Jackson", difficulty: "easy" },
        { word: "Madonna", difficulty: "easy" },
        { word: "Elvis Presley", difficulty: "easy" },
        { word: "Queen", difficulty: "easy" },
        { word: "Rolling Stones", difficulty: "easy" },
        { word: "Beyoncé", difficulty: "easy" },
        { word: "Taylor Swift", difficulty: "easy" },
        { word: "Lady Gaga", difficulty: "easy" },
        { word: "Justin Bieber", difficulty: "easy" },
        { word: "Led Zeppelin", difficulty: "hard" },
        { word: "Pink Floyd", difficulty: "hard" },
        { word: "Fleetwood Mac", difficulty: "hard" },
        { word: "Red Hot Chili Peppers", difficulty: "hard" },
        { word: "Nine Inch Nails", difficulty: "hard" },
        { word: "The Smashing Pumpkins", difficulty: "hard" },
        { word: "Rage Against the Machine", difficulty: "hard" },
        { word: "Radiohead", difficulty: "hard" },
        { word: "The Cure", difficulty: "hard" },
        { word: "Depeche Mode", difficulty: "hard" }
      ],
    "TV Shows": [
        { word: "Friends", difficulty: "easy" },
        { word: "Game of Thrones", difficulty: "easy" },
        { word: "Breaking Bad", difficulty: "easy" },
        { word: "The Office", difficulty: "easy" },
        { word: "Stranger Things", difficulty: "easy" },
        { word: "Grey's Anatomy", difficulty: "easy" },
        { word: "The Simpsons", difficulty: "easy" },
        { word: "Seinfeld", difficulty: "easy" },
        { word: "The Big Bang Theory", difficulty: "easy" },
        { word: "How I Met Your Mother", difficulty: "easy" },
        { word: "Twin Peaks", difficulty: "hard" },
        { word: "Black Mirror", difficulty: "hard" },
        { word: "The Crown", difficulty: "hard" },
        { word: "True Detective", difficulty: "hard" },
        { word: "The Handmaid's Tale", difficulty: "hard" },
        { word: "Mad Men", difficulty: "hard" },
        { word: "Westworld", difficulty: "hard" },
        { word: "The Mandalorian", difficulty: "hard" },
        { word: "The Sopranos", difficulty: "hard" },
        { word: "Better Call Saul", difficulty: "hard" }
      ],
    "Technology": [
        { word: "Smartphone", difficulty: "easy" },
        { word: "Laptop", difficulty: "easy" },
        { word: "Internet", difficulty: "easy" },
        { word: "Wi-Fi", difficulty: "easy" },
        { word: "Bluetooth", difficulty: "easy" },
        { word: "Tablet", difficulty: "easy" },
        { word: "Smartwatch", difficulty: "easy" },
        { word: "Drone", difficulty: "easy" },
        { word: "Virtual Reality", difficulty: "easy" },
        { word: "3D Printing", difficulty: "easy" },
        { word: "Artificial Intelligence", difficulty: "hard" },
        { word: "Blockchain", difficulty: "hard" },
        { word: "Quantum Computing", difficulty: "hard" },
        { word: "Machine Learning", difficulty: "hard" },
        { word: "Augmented Reality", difficulty: "hard" },
        { word: "Internet of Things", difficulty: "hard" },
        { word: "Neural Networks", difficulty: "hard" },
        { word: "Cybersecurity", difficulty: "hard" },
        { word: "Autonomous Vehicles", difficulty: "hard" },
        { word: "Cryptocurrency", difficulty: "hard" }
      ],
    "Fashion": [
        { word: "Dress", difficulty: "easy" },
        { word: "Jeans", difficulty: "easy" },
        { word: "T-shirt", difficulty: "easy" },
        { word: "Sneakers", difficulty: "easy" },
        { word: "Jacket", difficulty: "easy" },
        { word: "Hat", difficulty: "easy" },
        { word: "Sunglasses", difficulty: "easy" },
        { word: "Scarf", difficulty: "easy" },
        { word: "Skirt", difficulty: "easy" },
        { word: "Suit", difficulty: "easy" },
        { word: "Haute Couture", difficulty: "hard" },
        { word: "Little Black Dress", difficulty: "hard" },
        { word: "Power Suit", difficulty: "hard" },
        { word: "Trench Coat", difficulty: "hard" },
        { word: "Catwalk", difficulty: "hard" },
        { word: "Fashion Week", difficulty: "hard" },
        { word: "Street Style", difficulty: "hard" },
        { word: "Capsule Wardrobe", difficulty: "hard" },
        { word: "Vintage Clothing", difficulty: "hard" },
        { word: "Sustainable Fashion", difficulty: "hard" }
      ],
    "Space": [
        { word: "Earth", difficulty: "easy" },
        { word: "Moon", difficulty: "easy" },
        { word: "Sun", difficulty: "easy" },
        { word: "Mars", difficulty: "easy" },
        { word: "Stars", difficulty: "easy" },
        { word: "Galaxy", difficulty: "easy" },
        { word: "Asteroid", difficulty: "easy" },
        { word: "Comet", difficulty: "easy" },
        { word: "Meteor", difficulty: "easy" },
        { word: "Satellite", difficulty: "easy" },
        { word: "Black Hole", difficulty: "hard" },
        { word: "Supernova", difficulty: "hard" },
        { word: "Light Year", difficulty: "hard" },
        { word: "Milky Way", difficulty: "hard" },
        { word: "Red Giant", difficulty: "hard" },
        { word: "White Dwarf", difficulty: "hard" },
        { word: "Event Horizon", difficulty: "hard" },
        { word: "Dark Matter", difficulty: "hard" },
        { word: "Cosmic Microwave Background", difficulty: "hard" },
        { word: "Gravitational Waves", difficulty: "hard" }
      ],
    "Mythology": [
        { word: "Zeus", difficulty: "easy" },
        { word: "Hercules", difficulty: "easy" },
        { word: "Thor", difficulty: "easy" },
        { word: "Medusa", difficulty: "easy" },
        { word: "Minotaur", difficulty: "easy" },
        { word: "Poseidon", difficulty: "easy" },
        { word: "Apollo", difficulty: "easy" },
        { word: "Athena", difficulty: "easy" },
        { word: "Hades", difficulty: "easy" },
        { word: "Pandora", difficulty: "easy" },
        { word: "Ragnarok", difficulty: "hard" },
        { word: "Prometheus", difficulty: "hard" },
        { word: "Persephone", difficulty: "hard" },
        { word: "Charon", difficulty: "hard" },
        { word: "Bifrost Bridge", difficulty: "hard" },
        { word: "Valkyrie", difficulty: "hard" },
        { word: "Fenrir", difficulty: "hard" },
        { word: "Yggdrasil", difficulty: "hard" },
        { word: "Chimera", difficulty: "hard" },
        { word: "Labyrinth of Crete", difficulty: "hard" }
      ],
    "Inventions": [
        { word: "Telephone", difficulty: "easy" },
        { word: "Light bulb", difficulty: "easy" },
        { word: "Airplane", difficulty: "easy" },
        { word: "Car", difficulty: "easy" },
        { word: "Television", difficulty: "easy" },
        { word: "Computer", difficulty: "easy" },
        { word: "Radio", difficulty: "easy" },
        { word: "Camera", difficulty: "easy" },
        { word: "Printing Press", difficulty: "easy" },
        { word: "Microwave", difficulty: "easy" },
        { word: "Steam Engine", difficulty: "hard" },
        { word: "Penicillin", difficulty: "hard" },
        { word: "Electric Motor", difficulty: "hard" },
        { word: "Thermometer", difficulty: "hard" },
        { word: "Stethoscope", difficulty: "hard" },
        { word: "Typewriter", difficulty: "hard" },
        { word: "Sewing Machine", difficulty: "hard" },
        { word: "Solar Panel", difficulty: "hard" },
        { word: "Barcode", difficulty: "hard" },
        { word: "Transistor", difficulty: "hard" }
      ],
    "Art & Artists": [
        { word: "Mona Lisa", difficulty: "easy" },
        { word: "Van Gogh", difficulty: "easy" },
        { word: "Picasso", difficulty: "easy" },
        { word: "Michelangelo", difficulty: "easy" },
        { word: "Da Vinci", difficulty: "easy" },
        { word: "The Starry Night", difficulty: "easy" },
        { word: "The Scream", difficulty: "easy" },
        { word: "The Last Supper", difficulty: "easy" },
        { word: "Water Lilies", difficulty: "easy" },
        { word: "The Persistence of Memory", difficulty: "easy" },
        { word: "Guernica", difficulty: "hard" },
        { word: "Sistine Chapel Ceiling", difficulty: "hard" },
        { word: "The Night Watch", difficulty: "hard" },
        { word: "American Gothic", difficulty: "hard" },
        { word: "The Kiss", difficulty: "hard" },
        { word: "The Birth of Venus", difficulty: "hard" },
        { word: "Girl with a Pearl Earring", difficulty: "hard" },
        { word: "The Garden of Earthly Delights", difficulty: "hard" },
        { word: "The Arnolfini Portrait", difficulty: "hard" },
        { word: "The Raft of the Medusa", difficulty: "hard" }
      ],
    "Video Games": [
        { word: "Mario", difficulty: "easy" },
        { word: "Zelda", difficulty: "easy" },
        { word: "Sonic", difficulty: "easy" },
        { word: "Tetris", difficulty: "easy" },
        { word: "Minecraft", difficulty: "easy" },
        { word: "Fortnite", difficulty: "easy" },
        { word: "Call of Duty", difficulty: "easy" },
        { word: "Pac-Man", difficulty: "easy" },
        { word: "Pokémon", difficulty: "easy" },
        { word: "Halo", difficulty: "easy" },
        { word: "Red Dead Redemption", difficulty: "hard" },
        { word: "Dark Souls", difficulty: "hard" },
        { word: "The Witcher", difficulty: "hard" },
        { word: "Bioshock", difficulty: "hard" },
        { word: "Half-Life", difficulty: "hard" },
        { word: "Mass Effect", difficulty: "hard" },
        { word: "Portal", difficulty: "hard" },
        { word: "Deus Ex", difficulty: "hard" },
        { word: "Stardew Valley", difficulty: "hard" },
        { word: "The Last of Us", difficulty: "hard" }
      ],
      "Philosophy": [
        { word: "Socrates", difficulty: "hard" },
        { word: "Plato", difficulty: "hard" },
        { word: "Aristotle", difficulty: "hard" },
        { word: "Confucius", difficulty: "hard" },
        { word: "Albert Camus", difficulty: "hard" }
        // Add more philosophy words here
    ],
    "Music": [
        { word: "Beyoncé", difficulty: "easy" },
        { word: "Freddie Mercury", difficulty: "hard" },
        { word: "Adele", difficulty: "easy" },
        { word: "Ed Sheeran", difficulty: "easy" },
        { word: "Taylor Swift", difficulty: "easy" }
        // Add more music-related words here
    ],
    "Movies & TV Shows": [
        { word: "Leonardo DiCaprio", difficulty: "easy" },
        { word: "Harry Potter", difficulty: "easy" },
        { word: "Star Wars", difficulty: "easy" },
        { word: "Game of Thrones", difficulty: "easy" },
        { word: "The Godfather", difficulty: "easy" }
        // Add more movies and TV shows here
    ],
    "History": [
        { word: "Barack Obama", difficulty: "easy" },
        { word: "World War II", difficulty: "hard" },
        { word: "Nelson Mandela", difficulty: "hard" },
        { word: "Cleopatra", difficulty: "hard" },
        { word: "French Revolution", difficulty: "hard" }
        // Add more history-related words here
    ],
    "Science": [
        { word: "Gravity", difficulty: "easy" },
        { word: "Relativity", difficulty: "hard" },
        { word: "Evolution", difficulty: "hard" },
        { word: "String Theory", difficulty: "hard" },
        { word: "Hubble Space Telescope", difficulty: "hard" }
        // Add more science-related words here
    ],
    "Sports": [
        { word: "Lionel Messi", difficulty: "easy" },
        { word: "Serena Williams", difficulty: "easy" },
        { word: "Usain Bolt", difficulty: "easy" },
        { word: "FIFA World Cup", difficulty: "hard" },
        { word: "NBA Finals", difficulty: "hard" }
        // Add more sports-related words here
    ],
    "Art & Culture": [
        { word: "Mona Lisa", difficulty: "easy" },
        { word: "Michelangelo", difficulty: "hard" },
        { word: "Claude Monet", difficulty: "hard" },
        { word: "Vincent van Gogh", difficulty: "hard" },
        { word: "Sistine Chapel", difficulty: "hard" }
        // Add more art and culture-related words here
    ],
    "Technology": [
        { word: "Smartphone", difficulty: "easy" },
        { word: "Artificial Intelligence", difficulty: "hard" },
        { word: "Blockchain", difficulty: "hard" },
        { word: "Virtual Reality headset", difficulty: "hard" },
        { word: "Machine Learning", difficulty: "hard" }
        // Add more technology-related words here
    ],
};

const themes = {
    "Wedding Fever": [
        { word: "Bride", difficulty: "easy" },
        { word: "Groom", difficulty: "easy" },
        { word: "Wedding Cake", difficulty: "easy" },
        { word: "Bouquet", difficulty: "easy" },
        { word: "Honeymoon", difficulty: "easy" },
        { word: "Vows", difficulty: "easy" },
        { word: "Best Man", difficulty: "easy" },
        { word: "Maid of Honor", difficulty: "easy" },
        { word: "Wedding Ring", difficulty: "easy" },
        { word: "Reception", difficulty: "easy" },
        { word: "First Dance", difficulty: "hard" },
        { word: "Wedding Bells", difficulty: "hard" },
        { word: "Unity Candle", difficulty: "hard" },
        { word: "Wedding Planner", difficulty: "hard" },
        { word: "Flower Girl", difficulty: "hard" },
        { word: "Ring Bearer", difficulty: "hard" },
        { word: "Tuxedo", difficulty: "hard" },
        { word: "Wedding March", difficulty: "hard" },
        { word: "Bridal Shower", difficulty: "hard" },
        { word: "Bachelor Party", difficulty: "hard" }
    ],
    "Holiday Time": [
        { word: "Christmas tree", difficulty: "easy" },
        { word: "Santa Claus", difficulty: "easy" },
        { word: "Snowman", difficulty: "easy" },
        { word: "Gifts", difficulty: "easy" },
        { word: "Stockings", difficulty: "easy" },
        { word: "Reindeer", difficulty: "easy" },
        { word: "Sleigh", difficulty: "easy" },
        { word: "Caroling", difficulty: "easy" },
        { word: "Fireplace", difficulty: "easy" },
        { word: "Gingerbread", difficulty: "easy" },
        { word: "Ornament", difficulty: "easy" },
        { word: "Mistletoe", difficulty: "easy" },
        { word: "Eggnog", difficulty: "easy" },
        { word: "New Year's Eve", difficulty: "easy" },
        { word: "Hanukkah", difficulty: "easy" },
        { word: "Advent calendar", difficulty: "hard" },
        { word: "Kwanzaa", difficulty: "hard" },
        { word: "Yule log", difficulty: "hard" },
        { word: "Boxing Day", difficulty: "hard" },
        { word: "Epiphany", difficulty: "hard" },
        { word: "Menorah", difficulty: "hard" },
        { word: "Dreidel", difficulty: "hard" },
        { word: "Tinsel", difficulty: "hard" },
        { word: "Wassail", difficulty: "hard" },
        { word: "Nutcracker", difficulty: "hard" },
        { word: "Krampus", difficulty: "hard" },
        { word: "Solstice", difficulty: "hard" },
        { word: "Hogmanay", difficulty: "hard" },
        { word: "Black Friday", difficulty: "hard" },
        { word: "Feast of Seven Fishes", difficulty: "hard" }
      ],
    "Sports Event": [
        { word: "Olympic Games", difficulty: "easy" },
        { word: "World Cup", difficulty: "easy" },
        { word: "Super Bowl", difficulty: "easy" },
        { word: "Wimbledon", difficulty: "easy" },
        { word: "Tour de France", difficulty: "easy" },
        { word: "NBA Finals", difficulty: "easy" },
        { word: "Stanley Cup", difficulty: "easy" },
        { word: "Masters Tournament", difficulty: "easy" },
        { word: "Ryder Cup", difficulty: "easy" },
        { word: "Kentucky Derby", difficulty: "easy" },
        { word: "F1 Grand Prix", difficulty: "easy" },
        { word: "Rugby World Cup", difficulty: "easy" },
        { word: "MLB World Series", difficulty: "easy" },
        { word: "UFC Championship", difficulty: "easy" },
        { word: "Cricket World Cup", difficulty: "easy" },
        { word: "Heisman Trophy", difficulty: "hard" },
        { word: "The Ashes Series", difficulty: "hard" },
        { word: "UEFA Champions League", difficulty: "hard" },
        { word: "Copa America", difficulty: "hard" },
        { word: "La Liga Championship", difficulty: "hard" },
        { word: "Indy 500", difficulty: "hard" },
        { word: "PGA Championship", difficulty: "hard" },
        { word: "MotoGP", difficulty: "hard" },
        { word: "Commonwealth Games", difficulty: "hard" },
        { word: "Davis Cup", difficulty: "hard" },
        { word: "America's Cup", difficulty: "hard" },
        { word: "FA Cup Final", difficulty: "hard" },
        { word: "Six Nations Championship", difficulty: "hard" },
        { word: "Belmont Stakes", difficulty: "hard" }
      ],
    "Summer Vacation": [
        { word: "Beach", difficulty: "easy" },
        { word: "Surfing", difficulty: "easy" },
        { word: "Ice cream", difficulty: "easy" },
        { word: "Sandcastle", difficulty: "easy" },
        { word: "Sunbathing", difficulty: "easy" },
        { word: "Pool party", difficulty: "easy" },
        { word: "Barbecue", difficulty: "easy" },
        { word: "Camping", difficulty: "easy" },
        { word: "Hiking", difficulty: "easy" },
        { word: "Road trip", difficulty: "easy" },
        { word: "Water park", difficulty: "easy" },
        { word: "Fishing", difficulty: "easy" },
        { word: "Snorkeling", difficulty: "easy" },
        { word: "Jet skiing", difficulty: "easy" },
        { word: "Amusement park", difficulty: "easy" },
        { word: "Bonfire Night", difficulty: "hard" },
        { word: "Island Hopping", difficulty: "hard" },
        { word: "Deep-sea Fishing", difficulty: "hard" },
        { word: "Scenic Route", difficulty: "hard" },
        { word: "Guided Tour", difficulty: "hard" },
        { word: "Outdoor Concert", difficulty: "hard" },
        { word: "Nature Trail", difficulty: "hard" },
        { word: "Paddle Boarding", difficulty: "hard" },
        { word: "Paragliding", difficulty: "hard" },
        { word: "Cliff Diving", difficulty: "hard" },
        { word: "Kayaking", difficulty: "hard" },
        { word: "Wildlife Safari", difficulty: "hard" },
        { word: "Scuba Diving", difficulty: "hard" },
        { word: "Mountain Biking", difficulty: "hard" },
        { word: "Hot Air Balloon Ride", difficulty: "hard" }
      ],
    "Halloween Party": [
        { word: "Pumpkin", difficulty: "easy" },
        { word: "Ghost", difficulty: "easy" },
        { word: "Witch", difficulty: "easy" },
        { word: "Costume", difficulty: "easy" },
        { word: "Candy", difficulty: "easy" },
        { word: "Jack-o'-lantern", difficulty: "easy" },
        { word: "Haunted house", difficulty: "easy" },
        { word: "Skeleton", difficulty: "easy" },
        { word: "Vampire", difficulty: "easy" },
        { word: "Zombie", difficulty: "easy" },
        { word: "Trick-or-treat", difficulty: "easy" },
        { word: "Black cat", difficulty: "easy" },
        { word: "Spider web", difficulty: "easy" },
        { word: "Bat", difficulty: "easy" },
        { word: "Mask", difficulty: "easy" },
        { word: "Frankenstein's Monster", difficulty: "hard" },
        { word: "Dracula's Castle", difficulty: "hard" },
        { word: "Witch's Brew", difficulty: "hard" },
        { word: "Spooky Stories", difficulty: "hard" },
        { word: "Full Moon Night", difficulty: "hard" },
        { word: "Graveyard Shift", difficulty: "hard" },
        { word: "Poltergeist", difficulty: "hard" },
        { word: "Werewolf Transformation", difficulty: "hard" },
        { word: "Creepy Crawlies", difficulty: "hard" },
        { word: "Phantom of the Opera", difficulty: "hard" },
        { word: "Haunted Forest", difficulty: "hard" },
        { word: "Sleepy Hollow", difficulty: "hard" },
        { word: "Blood Moon", difficulty: "hard" },
        { word: "Scarecrow", difficulty: "hard" },
        { word: "Halloween Parade", difficulty: "hard" }
      ],
    "Christmas Celebration": [
        { word: "Santa Claus", difficulty: "easy" },
        { word: "Christmas tree", difficulty: "easy" },
        { word: "Snowman", difficulty: "easy" },
        { word: "Gifts", difficulty: "easy" },
        { word: "Stockings", difficulty: "easy" },
        { word: "Reindeer", difficulty: "easy" },
        { word: "Sleigh", difficulty: "easy" },
        { word: "Caroling", difficulty: "easy" },
        { word: "Fireplace", difficulty: "easy" },
        { word: "Gingerbread", difficulty: "easy" },
        { word: "Ornament", difficulty: "easy" },
        { word: "Mistletoe", difficulty: "easy" },
        { word: "Eggnog", difficulty: "easy" },
        { word: "New Year's Eve", difficulty: "easy" },
        { word: "Hanukkah", difficulty: "easy" },
        { word: "Advent Calendar", difficulty: "hard" },
        { word: "Kwanzaa", difficulty: "hard" },
        { word: "Yule Log", difficulty: "hard" },
        { word: "Boxing Day", difficulty: "hard" },
        { word: "Epiphany", difficulty: "hard" },
        { word: "Menorah", difficulty: "hard" },
        { word: "Dreidel", difficulty: "hard" },
        { word: "Tinsel", difficulty: "hard" },
        { word: "Wassail", difficulty: "hard" },
        { word: "Nutcracker", difficulty: "hard" },
        { word: "Krampus", difficulty: "hard" },
        { word: "Solstice", difficulty: "hard" },
        { word: "Hogmanay", difficulty: "hard" },
        { word: "Black Friday", difficulty: "hard" },
        { word: "Feast of Seven Fishes", difficulty: "hard" }
      ],
    "Back to School": [
        { word: "Homework", difficulty: "easy" },
        { word: "Backpack", difficulty: "easy" },
        { word: "Teacher", difficulty: "easy" },
        { word: "Classroom", difficulty: "easy" },
        { word: "Desk", difficulty: "easy" },
        { word: "Notebook", difficulty: "easy" },
        { word: "Pencil", difficulty: "easy" },
        { word: "Textbook", difficulty: "easy" },
        { word: "Lunchbox", difficulty: "easy" },
        { word: "Bus", difficulty: "easy" },
        { word: "Recess", difficulty: "easy" },
        { word: "Blackboard", difficulty: "easy" },
        { word: "Calculator", difficulty: "easy" },
        { word: "Ruler", difficulty: "easy" },
        { word: "School Bell", difficulty: "easy" },
        { word: "Parent-Teacher Conference", difficulty: "hard" },
        { word: "Science Fair Project", difficulty: "hard" },
        { word: "Field Trip", difficulty: "hard" },
        { word: "Honor Roll", difficulty: "hard" },
        { word: "Extracurricular Activities", difficulty: "hard" },
        { word: "Locker Combination", difficulty: "hard" },
        { word: "Study Group", difficulty: "hard" },
        { word: "Class President", difficulty: "hard" },
        { word: "Graduation Ceremony", difficulty: "hard" },
        { word: "Debate Club", difficulty: "hard" },
        { word: "School Assembly", difficulty: "hard" },
        { word: "Art Class", difficulty: "hard" },
        { word: "Gymnasium", difficulty: "hard" },
        { word: "History Lesson", difficulty: "hard" },
        { word: "Report Card", difficulty: "hard" }
      ],
    "Music Festival": [
        { word: "Stage", difficulty: "easy" },
        { word: "Band", difficulty: "easy" },
        { word: "Audience", difficulty: "easy" },
        { word: "Microphone", difficulty: "easy" },
        { word: "Guitar", difficulty: "easy" },
        { word: "Drums", difficulty: "easy" },
        { word: "DJ", difficulty: "easy" },
        { word: "Dance", difficulty: "easy" },
        { word: "Lights", difficulty: "easy" },
        { word: "Ticket", difficulty: "easy" },
        { word: "Camping", difficulty: "easy" },
        { word: "Tent", difficulty: "easy" },
        { word: "Soundcheck", difficulty: "easy" },
        { word: "Setlist", difficulty: "easy" },
        { word: "Encore", difficulty: "easy" },
        { word: "Backstage Pass", difficulty: "hard" },
        { word: "Crowd Surfing", difficulty: "hard" },
        { word: "Headliner", difficulty: "hard" },
        { word: "Festival Wristband", difficulty: "hard" },
        { word: "VIP Area", difficulty: "hard" },
        { word: "Acoustic Set", difficulty: "hard" },
        { word: "Merchandise Stand", difficulty: "hard" },
        { word: "Mosh Pit", difficulty: "hard" },
        { word: "Opening Act", difficulty: "hard" },
        { word: "Roadies", difficulty: "hard" },
        { word: "Tour Bus", difficulty: "hard" },
        { word: "Sound Engineer", difficulty: "hard" },
        { word: "Festival Grounds", difficulty: "hard" },
        { word: "Food Truck", difficulty: "hard" },
        { word: "Festival Vibes", difficulty: "hard" }
      ],
    "Movie Night": [
        { word: "Popcorn", difficulty: "easy" },
        { word: "Movie", difficulty: "easy" },
        { word: "Ticket", difficulty: "easy" },
        { word: "Director", difficulty: "easy" },
        { word: "Actor", difficulty: "easy" },
        { word: "Theater", difficulty: "easy" },
        { word: "Screen", difficulty: "easy" },
        { word: "Trailer", difficulty: "easy" },
        { word: "Snack", difficulty: "easy" },
        { word: "Seat", difficulty: "easy" },
        { word: "Projector", difficulty: "easy" },
        { word: "Credits", difficulty: "easy" },
        { word: "Scene", difficulty: "easy" },
        { word: "Genre", difficulty: "easy" },
        { word: "Plot", difficulty: "easy" },
        { word: "Cinematic Experience", difficulty: "hard" },
        { word: "Red Carpet Event", difficulty: "hard" },
        { word: "Independent Film", difficulty: "hard" },
        { word: "Blockbuster Hit", difficulty: "hard" },
        { word: "Special Effects", difficulty: "hard" },
        { word: "Box Office", difficulty: "hard" },
        { word: "Movie Marathon", difficulty: "hard" },
        { word: "Midnight Screening", difficulty: "hard" },
        { word: "Dolby Surround Sound", difficulty: "hard" },
        { word: "Film Festival", difficulty: "hard" },
        { word: "Cult Classic", difficulty: "hard" },
        { word: "Behind the Scenes", difficulty: "hard" },
        { word: "Movie Franchise", difficulty: "hard" },
        { word: "Character Development", difficulty: "hard" },
        { word: "Post-Credit Scene", difficulty: "hard" }
      ],
    "Adventure Trip": [
        { word: "Hiking", difficulty: "easy" },
        { word: "Backpacking", difficulty: "easy" },
        { word: "Camping", difficulty: "easy" },
        { word: "Rafting", difficulty: "easy" },
        { word: "Climbing", difficulty: "easy" },
        { word: "Road Trip", difficulty: "easy" },
        { word: "Jungle", difficulty: "easy" },
        { word: "Mountain", difficulty: "easy" },
        { word: "River", difficulty: "easy" },
        { word: "Desert", difficulty: "easy" },
        { word: "Beach", difficulty: "easy" },
        { word: "Waterfall", difficulty: "easy" },
        { word: "Wildlife", difficulty: "easy" },
        { word: "Campfire", difficulty: "easy" },
        { word: "Trail", difficulty: "easy" },
        { word: "Expedition", difficulty: "hard" },
        { word: "Survival Skills", difficulty: "hard" },
        { word: "Orienteering", difficulty: "hard" },
        { word: "Rock Climbing", difficulty: "hard" },
        { word: "Glacier Hiking", difficulty: "hard" },
        { word: "Desert Safari", difficulty: "hard" },
        { word: "River Rafting", difficulty: "hard" },
        { word: "Forest Trekking", difficulty: "hard" },
        { word: "Mountain Biking", difficulty: "hard" },
        { word: "Cave Exploration", difficulty: "hard" },
        { word: "Coastal Walk", difficulty: "hard" },
        { word: "Off-Road Adventure", difficulty: "hard" },
        { word: "High-Altitude Climb", difficulty: "hard" },
        { word: "Scuba Diving", difficulty: "hard" },
        { word: "Paragliding", difficulty: "hard" }
      ]      
    // Add other themes with their words and difficulties here
};