const categories = {
  "History": [
    { word: "World War I", difficulty: "easy" },
    { word: "World War II", difficulty: "easy" },
    { word: "Industrial Revolution", difficulty: "easy" },
    { word: "American Revolution", difficulty: "easy" },
    { word: "French Revolution", difficulty: "easy" },
    { word: "Roman Empire", difficulty: "easy" },
    { word: "Ancient Egypt", difficulty: "easy" },
    { word: "Cold War", difficulty: "easy" },
    { word: "The Renaissance", difficulty: "easy" },
    { word: "Alexander the Great", difficulty: "easy" },
    { word: "Fall of Constantinople", difficulty: "hard" },
    { word: "Treaty of Versailles", difficulty: "hard" },
    { word: "Ottoman Empire", difficulty: "hard" },
    { word: "Battle of Waterloo", difficulty: "hard" },
    { word: "Crusades", difficulty: "easy" },
    { word: "Genghis Khan", difficulty: "easy" },
    { word: "Marco Polo", difficulty: "easy" },
    { word: "Hannibal", difficulty: "hard" },
    { word: "Mongol Empire", difficulty: "hard" },
    { word: "Boston Tea Party", difficulty: "easy" },
    { word: "Magna Carta", difficulty: "hard" },
    { word: "Napoleon Bonaparte", difficulty: "easy" },
    { word: "Soviet Union", difficulty: "easy" },
    { word: "Battle of Gettysburg", difficulty: "hard" },
    { word: "Sparta", difficulty: "easy" },
    { word: "Joan of Arc", difficulty: "easy" },
    { word: "The Black Plague", difficulty: "easy" },
    { word: "Ancient Greece", difficulty: "easy" },
    { word: "Vikings", difficulty: "easy" },
    { word: "Mayflower", difficulty: "easy" },
    { word: "Titanic", difficulty: "easy" },
    { word: "Pearl Harbor", difficulty: "easy" },
    { word: "Leonardo da Vinci", difficulty: "easy" },
    { word: "Socrates", difficulty: "easy" },
    { word: "Alexander Hamilton", difficulty: "hard" },
    { word: "Sumerians", difficulty: "hard" },
    { word: "King Tutankhamun", difficulty: "easy" },
    { word: "Medieval Period", difficulty: "easy" },
    { word: "Byzantine Empire", difficulty: "hard" },
    { word: "Cuban Missile Crisis", difficulty: "easy" },
    { word: "Rosa Parks", difficulty: "easy" },
    { word: "Louis XIV", difficulty: "hard" },
    { word: "Harlem Renaissance", difficulty: "hard" },
    { word: "Martin Luther King Jr.", difficulty: "easy" },
    { word: "Berlin Wall", difficulty: "easy" },
    { word: "Emancipation Proclamation", difficulty: "hard" },
    { word: "Salem Witch Trials", difficulty: "hard" },
    { word: "Columbus' First Voyage", difficulty: "easy" },
    { word: "Feudalism", difficulty: "hard" },
    { word: "Barack Obama", difficulty: "easy" },
    { word: "World War II", difficulty: "hard" },
    { word: "Nelson Mandela", difficulty: "hard" },
    { word: "Cleopatra", difficulty: "hard" },
    { word: "French Revolution", difficulty: "hard" },
    { word: "Socrates", difficulty: "hard" },
    { word: "Plato", difficulty: "hard" },
    { word: "Aristotle", difficulty: "hard" },
    { word: "Confucius", difficulty: "hard" },
    { word: "Albert Camus", difficulty: "hard" },
    { word: "World War I", difficulty: "easy" },
    { word: "World War II", difficulty: "easy" },
    { word: "Moon Landing", difficulty: "easy" },
    { word: "American Revolution", difficulty: "easy" },
    { word: "French Revolution", difficulty: "easy" },
    { word: "Industrial Revolution", difficulty: "easy" },
    { word: "Civil Rights Movement", difficulty: "easy" },
    { word: "Fall of Berlin Wall", difficulty: "easy" },
    { word: "Renaissance", difficulty: "easy" },
    { word: "Great Depression", difficulty: "easy" },
    { word: "Signing of the Magna Carta", difficulty: "hard" },
    { word: "Battle of Hastings", difficulty: "hard" },
    { word: "Cuban Missile Crisis", difficulty: "hard" },
    { word: "Boston Tea Party", difficulty: "hard" },
    { word: "Spanish Inquisition", difficulty: "hard" },
    { word: "Storming of the Bastille", difficulty: "hard" },
    { word: "Salem Witch Trials", difficulty: "hard" },
    { word: "Treaty of Versailles", difficulty: "hard" },
    { word: "Fall of Constantinople", difficulty: "hard" },
    { word: "Berlin Airlift", difficulty: "hard" },
  ],
  "Geography": [
    { word: "Mount Everest", difficulty: "easy" },
    { word: "Amazon River", difficulty: "easy" },
    { word: "Sahara Desert", difficulty: "easy" },
    { word: "Great Barrier Reef", difficulty: "easy" },
    { word: "Nile River", difficulty: "easy" },
    { word: "Grand Canyon", difficulty: "easy" },
    { word: "Rocky Mountains", difficulty: "easy" },
    { word: "Himalayas", difficulty: "easy" },
    { word: "Lake Baikal", difficulty: "hard" },
    { word: "Andes Mountains", difficulty: "easy" },
    { word: "Mekong River", difficulty: "hard" },
    { word: "Atacama Desert", difficulty: "hard" },
    { word: "Victoria Falls", difficulty: "easy" },
    { word: "Gobi Desert", difficulty: "easy" },
    { word: "Great Wall of China", difficulty: "easy" },
    { word: "Mount Kilimanjaro", difficulty: "easy" },
    { word: "Mediterranean Sea", difficulty: "easy" },
    { word: "Bermuda Triangle", difficulty: "easy" },
    { word: "Angel Falls", difficulty: "hard" },
    { word: "Dead Sea", difficulty: "easy" },
    { word: "Yosemite National Park", difficulty: "easy" },
    { word: "Machu Picchu", difficulty: "easy" },
    { word: "Antarctica", difficulty: "easy" },
    { word: "Galapagos Islands", difficulty: "hard" },
    { word: "Patagonia", difficulty: "hard" },
    { word: "Amazon Rainforest", difficulty: "easy" },
    { word: "Niagara Falls", difficulty: "easy" },
    { word: "Siberia", difficulty: "easy" },
    { word: "Mount Fuji", difficulty: "easy" },
    { word: "Iceland", difficulty: "easy" },
    { word: "Tasmania", difficulty: "hard" },
    { word: "Borneo", difficulty: "hard" },
    { word: "K2", difficulty: "hard" },
    { word: "Lake Titicaca", difficulty: "hard" },
    { word: "Serengeti", difficulty: "easy" },
    { word: "Ural Mountains", difficulty: "hard" },
    { word: "Red Sea", difficulty: "easy" },
    { word: "Baltic Sea", difficulty: "easy" },
    { word: "Caspian Sea", difficulty: "hard" },
    { word: "Great Plains", difficulty: "easy" },
    { word: "Cape of Good Hope", difficulty: "easy" },
    { word: "Balkan Peninsula", difficulty: "hard" },
    { word: "Tierra del Fuego", difficulty: "hard" },
    { word: "Hokkaido", difficulty: "hard" },
    { word: "Lake Victoria", difficulty: "easy" },
    { word: "Scandinavia", difficulty: "easy" },
    { word: "Carpathian Mountains", difficulty: "hard" },
    { word: "Rock of Gibraltar", difficulty: "easy" },
    { word: "Yucatan Peninsula", difficulty: "hard" },
    { word: "Mountain", difficulty: "easy" },
    { word: "River", difficulty: "easy" },
    { word: "Ocean", difficulty: "easy" },
    { word: "Desert", difficulty: "easy" },
    { word: "Valley", difficulty: "easy" },
    { word: "Island", difficulty: "easy" },
    { word: "Volcano", difficulty: "easy" },
    { word: "Peninsula", difficulty: "easy" },
    { word: "Plateau", difficulty: "easy" },
    { word: "Glacier", difficulty: "easy" },
    { word: "Equator", difficulty: "hard" },
    { word: "Prime Meridian", difficulty: "hard" },
    { word: "International Date Line", difficulty: "hard" },
    { word: "Tropic of Cancer", difficulty: "hard" },
    { word: "Tropic of Capricorn", difficulty: "hard" },
    { word: "Isthmus", difficulty: "hard" },
    { word: "Archipelago", difficulty: "hard" },
    { word: "Delta", difficulty: "hard" },
    { word: "Estuary", difficulty: "hard" },
    { word: "Atoll", difficulty: "hard" },
    { word: "Paris", difficulty: "easy" },
    { word: "Great Wall of China", difficulty: "medium" },
    { word: "Brazil", difficulty: "easy" },
    { word: "Africa", difficulty: "easy" },
    { word: "Statue of Liberty", difficulty: "medium" },
    { word: "Nile River", difficulty: "medium" },
    { word: "Lake Victoria", difficulty: "medium" },
    { word: "Mount Everest", difficulty: "medium" },
    { word: "New York City", difficulty: "medium" },
    { word: "Colosseum", difficulty: "medium" },
    { word: "Japan", difficulty: "easy" },
    { word: "Europe", difficulty: "medium" },
    { word: "Eiffel Tower", difficulty: "medium" },
    { word: "Amazon River", difficulty: "medium" },
    { word: "Lake Baikal", difficulty: "medium" },
    { word: "Matterhorn", difficulty: "medium" },
    { word: "China", difficulty: "easy" },
    { word: "Asia", difficulty: "medium" },
    { word: "Golden Gate Bridge", difficulty: "medium" },
    { word: "Mississippi River", difficulty: "medium" },
    { word: "Lake Superior", difficulty: "medium" },
    { word: "K2", difficulty: "medium" },
    { word: "Danube River", difficulty: "medium" },
    { word: "Lake Titicaca", difficulty: "medium" },
    { word: "Kilimanjaro", difficulty: "medium" },
    { word: "Sydney Opera House", difficulty: "medium" },
    { word: "Colorado River", difficulty: "medium" },
    { word: "Lake Tahoe", difficulty: "medium" },
    { word: "Mont Blanc", difficulty: "medium" },
    { word: "Lake Ontario", difficulty: "medium" },
    { word: "Yangtze River", difficulty: "medium" },
    { word: "Mount Kilimanjaro", difficulty: "medium" },
    { word: "Mount Vesuvius", difficulty: "medium" },
    { word: "Great Barrier Reef", difficulty: "medium" },
    { word: "Machu Picchu", difficulty: "medium" },
    { word: "Neuschwanstein Castle", difficulty: "medium" },
    { word: "Gobi Desert", difficulty: "medium" },
    { word: "Burj Khalifa", difficulty: "medium" },
    { word: "Volga River", difficulty: "medium" },
    { word: "Lake Michigan", difficulty: "medium" },
    { word: "Ben Nevis", difficulty: "medium" },
    { word: "Mount St. Helens", difficulty: "medium" },
    { word: "Skellig Michael", difficulty: "medium" },
    { word: "Ganges River", difficulty: "medium" },
    { word: "Lake Champlain", difficulty: "medium" },
    { word: "Petra", difficulty: "medium" },
    { word: "Mount McKinley", difficulty: "medium" },
    { word: "Emerald Isle", difficulty: "medium" },
    { word: "Niagara Falls", difficulty: "medium" },
    { word: "Isle Royale", difficulty: "medium" },
    { word: "Denver", difficulty: "medium" },
    { word: "Mauna Kea", difficulty: "medium" },
    { word: "Forbidden City", difficulty: "medium" },
    { word: "Thames River", difficulty: "medium" },
    { word: "Lake Powell", difficulty: "medium" },
    { word: "Atlantis", difficulty: "medium" },
    { word: "Paris", difficulty: "easy" },
    { word: "Great Wall of China", difficulty: "hard" },
    { word: "Nile River", difficulty: "hard" },
    { word: "Amazon River", difficulty: "hard" },
    { word: "Mount Everest", difficulty: "hard" },
    { word: "Eiffel Tower", difficulty: "easy" },
    { word: "Great Wall of China", difficulty: "easy" },
    { word: "Statue of Liberty", difficulty: "easy" },
    { word: "Big Ben", difficulty: "easy" },
    { word: "Colosseum", difficulty: "easy" },
    { word: "Pyramids of Giza", difficulty: "easy" },
    { word: "Machu Picchu", difficulty: "easy" },
    { word: "Taj Mahal", difficulty: "easy" },
    { word: "Sydney Opera House", difficulty: "easy" },
    { word: "Mount Rushmore", difficulty: "easy" },
    { word: "Christ the Redeemer", difficulty: "hard" },
    { word: "Golden Gate Bridge", difficulty: "hard" },
    { word: "Stonehenge", difficulty: "hard" },
    { word: "Neuschwanstein Castle", difficulty: "hard" },
    { word: "Leaning Tower of Pisa", difficulty: "hard" },
    { word: "Angkor Wat", difficulty: "hard" },
    { word: "Chichen Itza", difficulty: "hard" },
    { word: "Sagrada Familia", difficulty: "hard" },
    { word: "Burj Khalifa", difficulty: "hard" },
    { word: "Alhambra Palace", difficulty: "hard" }
  ],
  "Science & Technology": [
    { word: "DNA", difficulty: "easy" },
    { word: "Artificial Intelligence", difficulty: "easy" },
    { word: "Quantum Mechanics", difficulty: "easy" },
    { word: "Space Exploration", difficulty: "easy" },
    { word: "Solar System", difficulty: "easy" },
    { word: "Genetics", difficulty: "easy" },
    { word: "Internet of Things (IoT)", difficulty: "easy" },
    { word: "Climate Change", difficulty: "easy" },
    { word: "Nanotechnology", difficulty: "hard" },
    { word: "Robotics", difficulty: "easy" },
    { word: "Blockchain", difficulty: "hard" },
    { word: "Virtual Reality", difficulty: "easy" },
    { word: "Cybersecurity", difficulty: "easy" },
    { word: "Biotechnology", difficulty: "hard" },
    { word: "Electric Vehicles", difficulty: "easy" },
    { word: "Machine Learning", difficulty: "easy" },
    { word: "3D Printing", difficulty: "easy" },
    { word: "Renewable Energy", difficulty: "easy" },
    { word: "CRISPR", difficulty: "hard" },
    { word: "Drones", difficulty: "easy" },
    { word: "Augmented Reality", difficulty: "easy" },
    { word: "Quantum Computing", difficulty: "hard" },
    { word: "Cloud Computing", difficulty: "easy" },
    { word: "Medical Imaging", difficulty: "hard" },
    { word: "Artificial Neural Networks", difficulty: "hard" },
    { word: "Fusion Energy", difficulty: "hard" },
    { word: "Smartphones", difficulty: "easy" },
    { word: "Space Telescope", difficulty: "easy" },
    { word: "The Human Genome Project", difficulty: "hard" },
    { word: "Wireless Technology", difficulty: "easy" },
    { word: "Internet", difficulty: "easy" },
    { word: "Satellite Technology", difficulty: "easy" },
    { word: "Bioinformatics", difficulty: "hard" },
    { word: "Renewable Resources", difficulty: "easy" },
    { word: "Geothermal Energy", difficulty: "hard" },
    { word: "Prosthetics", difficulty: "hard" },
    { word: "Space Junk", difficulty: "easy" },
    { word: "Telecommunications", difficulty: "easy" },
    { word: "Astronomy", difficulty: "easy" },
    { word: "Hydroponics", difficulty: "hard" },
    { word: "Data Science", difficulty: "easy" },
    { word: "Nuclear Fusion", difficulty: "hard" },
    { word: "Cyborgs", difficulty: "hard" },
    { word: "Neuroscience", difficulty: "hard" },
    { word: "3D Modeling", difficulty: "easy" },
    { word: "Internet Privacy", difficulty: "easy" },
    { word: "Space Tourism", difficulty: "easy" },
    { word: "Medical Robotics", difficulty: "hard" },
    { word: "Gravity", difficulty: "easy" },
    { word: "Relativity", difficulty: "hard" },
    { word: "Evolution", difficulty: "hard" },
    { word: "String Theory", difficulty: "hard" },
    { word: "Hubble Space Telescope", difficulty: "hard" },
    { word: "Smartphone", difficulty: "easy" },
    { word: "Artificial Intelligence", difficulty: "hard" },
    { word: "Blockchain", difficulty: "hard" },
    { word: "Virtual Reality headset", difficulty: "hard" },
    { word: "Machine Learning", difficulty: "hard" },
    { word: "Smartphone", difficulty: "easy" },
    { word: "Laptop", difficulty: "easy" },
    { word: "Internet", difficulty: "easy" },
    { word: "Wi-Fi", difficulty: "easy" },
    { word: "Bluetooth", difficulty: "easy" },
    { word: "Tablet", difficulty: "easy" },
    { word: "Smartwatch", difficulty: "easy" },
    { word: "Drone", difficulty: "easy" },
    { word: "Virtual Reality", difficulty: "easy" },
    { word: "3D Printing", difficulty: "easy" },
    { word: "Artificial Intelligence", difficulty: "hard" },
    { word: "Blockchain", difficulty: "hard" },
    { word: "Quantum Computing", difficulty: "hard" },
    { word: "Machine Learning", difficulty: "hard" },
    { word: "Augmented Reality", difficulty: "hard" },
    { word: "Internet of Things", difficulty: "hard" },
    { word: "Neural Networks", difficulty: "hard" },
    { word: "Cybersecurity", difficulty: "hard" },
    { word: "Autonomous Vehicles", difficulty: "hard" },
    { word: "Cryptocurrency", difficulty: "hard" },
  ],
  "Literature": [
    { word: "Romeo and Juliet", difficulty: "easy" },
    { word: "To Kill a Mockingbird", difficulty: "easy" },
    { word: "Harry Potter", difficulty: "easy" },
    { word: "The Great Gatsby", difficulty: "easy" },
    { word: "Moby Dick", difficulty: "easy" },
    { word: "1984", difficulty: "easy" },
    { word: "Pride and Prejudice", difficulty: "easy" },
    { word: "The Lord of the Rings", difficulty: "easy" },
    { word: "Hamlet", difficulty: "easy" },
    { word: "The Catcher in the Rye", difficulty: "easy" },
    { word: "War and Peace", difficulty: "hard" },
    { word: "Jane Eyre", difficulty: "easy" },
    { word: "Frankenstein", difficulty: "easy" },
    { word: "The Odyssey", difficulty: "easy" },
    { word: "Brave New World", difficulty: "easy" },
    { word: "Alice's Adventures in Wonderland", difficulty: "easy" },
    { word: "Dracula", difficulty: "easy" },
    { word: "The Adventures of Huckleberry Finn", difficulty: "easy" },
    { word: "Les Misérables", difficulty: "hard" },
    { word: "The Iliad", difficulty: "easy" },
    { word: "The Count of Monte Cristo", difficulty: "easy" },
    { word: "Don Quixote", difficulty: "hard" },
    { word: "The Hobbit", difficulty: "easy" },
    { word: "Gulliver's Travels", difficulty: "easy" },
    { word: "Anna Karenina", difficulty: "hard" },
    { word: "The Picture of Dorian Gray", difficulty: "easy" },
    { word: "Wuthering Heights", difficulty: "easy" },
    { word: "The Canterbury Tales", difficulty: "hard" },
    { word: "The Brothers Karamazov", difficulty: "hard" },
    { word: "One Hundred Years of Solitude", difficulty: "hard" },
    { word: "The Divine Comedy", difficulty: "hard" },
    { word: "The Sun Also Rises", difficulty: "easy" },
    { word: "The Handmaid's Tale", difficulty: "easy" },
    { word: "The Jungle Book", difficulty: "easy" },
    { word: "Fahrenheit 451", difficulty: "easy" },
    { word: "The Wind in the Willows", difficulty: "easy" },
    { word: "Crime and Punishment", difficulty: "hard" },
    { word: "Great Expectations", difficulty: "easy" },
    { word: "The Grapes of Wrath", difficulty: "easy" },
    { word: "Moby-Dick", difficulty: "easy" },
    { word: "Gone with the Wind", difficulty: "easy" },
    { word: "The Sound and the Fury", difficulty: "hard" },
    { word: "Catch-22", difficulty: "easy" },
    { word: "Lord of the Flies", difficulty: "easy" },
    { word: "The Hunger Games", difficulty: "easy" },
    { word: "The Martian Chronicles", difficulty: "hard" },
    { word: "A Tale of Two Cities", difficulty: "easy" },
    { word: "The Scarlet Letter", difficulty: "easy" },
    { word: "Middlemarch", difficulty: "hard" },
    { word: "Heart of Darkness", difficulty: "hard" }
  ],
  "Art and Culture": [
    { word: "Mona Lisa", difficulty: "easy" },
    { word: "Michelangelo", difficulty: "easy" },
    { word: "Renaissance", difficulty: "easy" },
    { word: "Pablo Picasso", difficulty: "easy" },
    { word: "Vincent van Gogh", difficulty: "easy" },
    { word: "Leonardo da Vinci", difficulty: "easy" },
    { word: "Impressionism", difficulty: "easy" },
    { word: "Sistine Chapel", difficulty: "easy" },
    { word: "Ballet", difficulty: "easy" },
    { word: "Opera", difficulty: "easy" },
    { word: "Andy Warhol", difficulty: "easy" },
    { word: "Shakespeare", difficulty: "easy" },
    { word: "Frida Kahlo", difficulty: "easy" },
    { word: "Gothic Architecture", difficulty: "easy" },
    { word: "Broadway", difficulty: "easy" },
    { word: "Surrealism", difficulty: "easy" },
    { word: "The Louvre", difficulty: "easy" },
    { word: "Film Noir", difficulty: "easy" },
    { word: "The Beatles", difficulty: "easy" },
    { word: "Hip Hop", difficulty: "easy" },
    { word: "Abstract Art", difficulty: "easy" },
    { word: "Theater", difficulty: "easy" },
    { word: "The Great Gatsby", difficulty: "easy" },
    { word: "Cubism", difficulty: "easy" },
    { word: "Broadway Musical", difficulty: "easy" },
    { word: "Rembrandt", difficulty: "easy" },
    { word: "Classical Music", difficulty: "easy" },
    { word: "Pop Art", difficulty: "easy" },
    { word: "Literary Classic", difficulty: "easy" },
    { word: "Rococo", difficulty: "easy" },
    { word: "Hollywood", difficulty: "easy" },
    { word: "Baroque Music", difficulty: "easy" },
    { word: "Romeo and Juliet", difficulty: "easy" },
    { word: "Dadaism", difficulty: "easy" },
    { word: "Guggenheim Museum", difficulty: "easy" },
    { word: "Abstract Expressionism", difficulty: "easy" },
    { word: "The Last Supper", difficulty: "easy" },
    { word: "Sculpture", difficulty: "easy" },
    { word: "Neo-Classicism", difficulty: "easy" },
    { word: "Modern Dance", difficulty: "easy" },
    { word: "Jazz", difficulty: "easy" },
    { word: "The Thinker", difficulty: "easy" },
    { word: "Street Art", difficulty: "easy" },
    { word: "The Alhambra", difficulty: "easy" },
    { word: "Graphic Novel", difficulty: "easy" },
    { word: "Classical Ballet", difficulty: "easy" },
    { word: "Folk Music", difficulty: "easy" },
    { word: "Romanticism", difficulty: "easy" },
    { word: "Mona Lisa", difficulty: "easy" },
    { word: "Michelangelo", difficulty: "hard" },
    { word: "Claude Monet", difficulty: "hard" },
    { word: "Vincent van Gogh", difficulty: "hard" },
    { word: "Sistine Chapel", difficulty: "hard" },
    { word: "Mona Lisa", difficulty: "easy" },
    { word: "Van Gogh", difficulty: "easy" },
    { word: "Picasso", difficulty: "easy" },
    { word: "Michelangelo", difficulty: "easy" },
    { word: "Da Vinci", difficulty: "easy" },
    { word: "The Starry Night", difficulty: "easy" },
    { word: "The Scream", difficulty: "easy" },
    { word: "The Last Supper", difficulty: "easy" },
    { word: "Water Lilies", difficulty: "easy" },
    { word: "The Persistence of Memory", difficulty: "easy" },
    { word: "Guernica", difficulty: "hard" },
    { word: "Sistine Chapel Ceiling", difficulty: "hard" },
    { word: "The Night Watch", difficulty: "hard" },
    { word: "American Gothic", difficulty: "hard" },
    { word: "The Kiss", difficulty: "hard" },
    { word: "The Birth of Venus", difficulty: "hard" },
    { word: "Girl with a Pearl Earring", difficulty: "hard" },
    { word: "The Garden of Earthly Delights", difficulty: "hard" },
    { word: "The Arnolfini Portrait", difficulty: "hard" },
    { word: "The Raft of the Medusa", difficulty: "hard" }
  ],
  "Music": [
    { word: "Beethoven", difficulty: "easy" },
    { word: "The Beatles", difficulty: "easy" },
    { word: "Rock and Roll", difficulty: "easy" },
    { word: "Mozart", difficulty: "easy" },
    { word: "Jazz", difficulty: "easy" },
    { word: "Hip Hop", difficulty: "easy" },
    { word: "Opera", difficulty: "easy" },
    { word: "Elvis Presley", difficulty: "easy" },
    { word: "Piano", difficulty: "easy" },
    { word: "Violin", difficulty: "easy" },
    { word: "Michael Jackson", difficulty: "easy" },
    { word: "Blues", difficulty: "easy" },
    { word: "The Rolling Stones", difficulty: "easy" },
    { word: "Country Music", difficulty: "easy" },
    { word: "Classical Music", difficulty: "easy" },
    { word: "Reggae", difficulty: "easy" },
    { word: "Guitar", difficulty: "easy" },
    { word: "Choir", difficulty: "easy" },
    { word: "Broadway Musical", difficulty: "easy" },
    { word: "Rap", difficulty: "easy" },
    { word: "Saxophone", difficulty: "easy" },
    { word: "Folk Music", difficulty: "easy" },
    { word: "Salsa", difficulty: "easy" },
    { word: "DJ", difficulty: "easy" },
    { word: "Chopin", difficulty: "easy" },
    { word: "Acoustic Guitar", difficulty: "easy" },
    { word: "Heavy Metal", difficulty: "easy" },
    { word: "Electronic Music", difficulty: "easy" },
    { word: "Opera Singer", difficulty: "easy" },
    { word: "Woodstock", difficulty: "easy" },
    { word: "Concerto", difficulty: "easy" },
    { word: "Drum Set", difficulty: "easy" },
    { word: "R&B", difficulty: "easy" },
    { word: "Baroque Music", difficulty: "easy" },
    { word: "Trumpet", difficulty: "easy" },
    { word: "Synthesizer", difficulty: "easy" },
    { word: "Festival", difficulty: "easy" },
    { word: "Marching Band", difficulty: "easy" },
    { word: "Singer-Songwriter", difficulty: "easy" },
    { word: "Motown", difficulty: "easy" },
    { word: "Orchestra", difficulty: "easy" },
    { word: "Grammy Awards", difficulty: "easy" },
    { word: "Conducting", difficulty: "easy" },
    { word: "Punk Rock", difficulty: "easy" },
    { word: "Bass Guitar", difficulty: "easy" },
    { word: "Songwriting", difficulty: "easy" },
    { word: "Keyboard", difficulty: "easy" },
    { word: "Rhythm and Blues", difficulty: "easy" },
    { word: "Beyoncé", difficulty: "easy" },
    { word: "Freddie Mercury", difficulty: "hard" },
    { word: "Adele", difficulty: "easy" },
    { word: "Ed Sheeran", difficulty: "easy" },
    { word: "Taylor Swift", difficulty: "easy" },
    { word: "The Beatles", difficulty: "easy" },
    { word: "Michael Jackson", difficulty: "easy" },
    { word: "Madonna", difficulty: "easy" },
    { word: "Elvis Presley", difficulty: "easy" },
    { word: "Queen", difficulty: "easy" },
    { word: "Rolling Stones", difficulty: "easy" },
    { word: "Beyoncé", difficulty: "easy" },
    { word: "Taylor Swift", difficulty: "easy" },
    { word: "Lady Gaga", difficulty: "easy" },
    { word: "Justin Bieber", difficulty: "easy" },
    { word: "Led Zeppelin", difficulty: "hard" },
    { word: "Pink Floyd", difficulty: "hard" },
    { word: "Fleetwood Mac", difficulty: "hard" },
    { word: "Red Hot Chili Peppers", difficulty: "hard" },
    { word: "Nine Inch Nails", difficulty: "hard" },
    { word: "The Smashing Pumpkins", difficulty: "hard" },
    { word: "Rage Against the Machine", difficulty: "hard" },
    { word: "Radiohead", difficulty: "hard" },
    { word: "The Cure", difficulty: "hard" },
    { word: "Depeche Mode", difficulty: "hard" },
  ],
  "Sports": [
    { word: "Football", difficulty: "easy" },
    { word: "Basketball", difficulty: "easy" },
    { word: "Soccer", difficulty: "easy" },
    { word: "Tennis", difficulty: "easy" },
    { word: "Golf", difficulty: "easy" },
    { word: "Baseball", difficulty: "easy" },
    { word: "Swimming", difficulty: "easy" },
    { word: "Boxing", difficulty: "easy" },
    { word: "Cricket", difficulty: "easy" },
    { word: "Rugby", difficulty: "easy" },
    { word: "Running", difficulty: "easy" },
    { word: "Volleyball", difficulty: "easy" },
    { word: "Ice Hockey", difficulty: "easy" },
    { word: "Table Tennis", difficulty: "easy" },
    { word: "Athletics", difficulty: "easy" },
    { word: "Cycling", difficulty: "easy" },
    { word: "Wrestling", difficulty: "easy" },
    { word: "Badminton", difficulty: "easy" },
    { word: "Formula 1", difficulty: "easy" },
    { word: "Martial Arts", difficulty: "easy" },
    { word: "Gymnastics", difficulty: "easy" },
    { word: "Surfing", difficulty: "easy" },
    { word: "Snowboarding", difficulty: "easy" },
    { word: "Skateboarding", difficulty: "easy" },
    { word: "Polo", difficulty: "easy" },
    { word: "Archery", difficulty: "easy" },
    { word: "Equestrian", difficulty: "easy" },
    { word: "Sailing", difficulty: "easy" },
    { word: "Darts", difficulty: "easy" },
    { word: "Snooker", difficulty: "easy" },
    { word: "Squash", difficulty: "easy" },
    { word: "Canoeing", difficulty: "easy" },
    { word: "Rowing", difficulty: "easy" },
    { word: "Triathlon", difficulty: "easy" },
    { word: "Netball", difficulty: "easy" },
    { word: "Pentathlon", difficulty: "easy" },
    { word: "Handball", difficulty: "easy" },
    { word: "Curling", difficulty: "easy" },
    { word: "Fencing", difficulty: "easy" },
    { word: "Lacrosse", difficulty: "easy" },
    { word: "Bobsleigh", difficulty: "easy" },
    { word: "Powerlifting", difficulty: "easy" },
    { word: "Mountaineering", difficulty: "easy" },
    { word: "Figure Skating", difficulty: "easy" },
    { word: "Biathlon", difficulty: "easy" },
    { word: "Taekwondo", difficulty: "easy" },
    { word: "Bowling", difficulty: "easy" },
    { word: "Water Polo", difficulty: "easy" },
    { word: "Goal", difficulty: "easy" },
    { word: "Ball", difficulty: "easy" },
    { word: "Kick", difficulty: "easy" },
    { word: "Pass", difficulty: "easy" },
    { word: "Referee", difficulty: "easy" },
    { word: "Goalkeeper", difficulty: "easy" },
    { word: "Red Card", difficulty: "easy" },
    { word: "Yellow Card", difficulty: "easy" },
    { word: "Foul", difficulty: "easy" },
    { word: "Offside", difficulty: "easy" },
    { word: "Penalty Kick", difficulty: "easy" },
    { word: "Corner Kick", difficulty: "easy" },
    { word: "Free Kick", difficulty: "easy" },
    { word: "Tackle", difficulty: "easy" },
    { word: "Header", difficulty: "easy" },
    { word: "Substitute", difficulty: "easy" },
    { word: "Captain", difficulty: "easy" },
    { word: "World Cup", difficulty: "easy" },
    { word: "Champions League", difficulty: "easy" },
    { word: "Premier League", difficulty: "easy" },
    { word: "La Liga", difficulty: "easy" },
    { word: "Serie A", difficulty: "easy" },
    { word: "Bundesliga", difficulty: "easy" },
    { word: "Messi", difficulty: "easy" },
    { word: "Ronaldo", difficulty: "easy" },
    { word: "Neymar", difficulty: "easy" },
    { word: "Mbappe", difficulty: "easy" },
    { word: "Zidane", difficulty: "easy" },
    { word: "Maradona", difficulty: "easy" },
    { word: "Pele", difficulty: "easy" },
    { word: "Beckenbauer", difficulty: "easy" },
    { word: "Wembley Stadium", difficulty: "easy" },
    { word: "Camp Nou", difficulty: "easy" },
    { word: "Santiago Bernabeu", difficulty: "easy" },
    { word: "Old Trafford", difficulty: "easy" },
    { word: "Anfield", difficulty: "easy" },
    { word: "Allianz Arena", difficulty: "easy" },
    { word: "FIFA", difficulty: "easy" },
    { word: "UEFA", difficulty: "easy" },
    { word: "Golden Boot", difficulty: "easy" },
    { word: "Golden Ball", difficulty: "easy" },
    { word: "Top Scorer", difficulty: "easy" },
    { word: "Hat-Trick", difficulty: "easy" },
    { word: "Own Goal", difficulty: "easy" },
    { word: "Touchdown", difficulty: "easy" },
    { word: "Basketball", difficulty: "easy" },
    { word: "Home Run", difficulty: "easy" },
    { word: "Ace", difficulty: "easy" },
    { word: "Birdie", difficulty: "easy" },
    { word: "Forehand", difficulty: "easy" },
    { word: "Backhand", difficulty: "easy" },
    { word: "Serve", difficulty: "easy" },
    { word: "Grand Slam", difficulty: "easy" },
    { word: "Wimbledon", difficulty: "easy" },
    { word: "Super Bowl", difficulty: "easy" },
    { word: "World Series", difficulty: "easy" },
    { word: "Olympics", difficulty: "easy" },
    { word: "Swimming", difficulty: "easy" },
    { word: "Golf", difficulty: "easy" },
    { word: "Tennis", difficulty: "easy" },
    { word: "Formula 1", difficulty: "easy" },
    { word: "Tour de France", difficulty: "easy" },
    { word: "Boxing", difficulty: "easy" },
    { word: "MMA", difficulty: "easy" },
    { word: "Wrestling", difficulty: "easy" },
    { word: "Snowboarding", difficulty: "easy" },
    { word: "Skiing", difficulty: "easy" },
    { word: "Surfing", difficulty: "easy" },
    { word: "Cricket", difficulty: "easy" },
    { word: "Rugby", difficulty: "easy" },
    { word: "Athletics", difficulty: "easy" },
    { word: "High Jump", difficulty: "easy" },
    { word: "Long Jump", difficulty: "easy" },
    { word: "Pole Vault", difficulty: "easy" },
    { word: "Javelin", difficulty: "easy" },
    { word: "Shot Put", difficulty: "easy" },
    { word: "Hockey", difficulty: "easy" },
    { word: "Baseball", difficulty: "easy" },
    { word: "Cycling", difficulty: "easy" },
    { word: "Karate", difficulty: "easy" },
    { word: "Taekwondo", difficulty: "easy" },
    { word: "Fencing", difficulty: "easy" },
    { word: "Archery", difficulty: "easy" },
    { word: "Equestrian", difficulty: "easy" },
    { word: "Sailing", difficulty: "easy" },
    { word: "Diving", difficulty: "easy" },
    { word: "Gymnastics", difficulty: "easy" },
    { word: "Pentathlon", difficulty: "easy" },
    { word: "Triathlon", difficulty: "easy" },
    { word: "Michael Jordan", difficulty: "easy" },
    { word: "Serena Williams", difficulty: "easy" },
    { word: "Usain Bolt", difficulty: "easy" },
    { word: "Muhammad Ali", difficulty: "easy" },
    { word: "Cristiano Ronaldo", difficulty: "easy" },
    { word: "Lionel Messi", difficulty: "easy" },
    { word: "Roger Federer", difficulty: "easy" },
    { word: "Tiger Woods", difficulty: "easy" },
    { word: "LeBron James", difficulty: "easy" },
    { word: "Michael Phelps", difficulty: "easy" },
    { word: "Simone Biles", difficulty: "easy" },
    { word: "Kobe Bryant", difficulty: "easy" },
    { word: "Wayne Gretzky", difficulty: "easy" },
    { word: "Mia Hamm", difficulty: "easy" },
    { word: "Babe Ruth", difficulty: "easy" },
    { word: "Rafael Nadal", difficulty: "easy" },
    { word: "Jackie Joyner-Kersee", difficulty: "easy" },
    { word: "Novak Djokovic", difficulty: "easy" },
    { word: "Martina Navratilova", difficulty: "easy" },
    { word: "Pele", difficulty: "easy" },
    { word: "Diego Maradona", difficulty: "easy" },
    { word: "Michael Schumacher", difficulty: "easy" },
    { word: "Sachin Tendulkar", difficulty: "easy" },
    { word: "Manny Pacquiao", difficulty: "easy" },
    { word: "Alex Morgan", difficulty: "easy" },
    { word: "Lionel Messi", difficulty: "easy" },
    { word: "Serena Williams", difficulty: "easy" },
    { word: "Usain Bolt", difficulty: "easy" },
    { word: "FIFA World Cup", difficulty: "hard" },
    { word: "NBA Finals", difficulty: "hard" },
    { word: "Goal", difficulty: "easy" },
    { word: "Penalty", difficulty: "easy" },
    { word: "Offside", difficulty: "easy" },
    { word: "Corner kick", difficulty: "easy" },
    { word: "Red card", difficulty: "easy" },
    { word: "Yellow card", difficulty: "easy" },
    { word: "Free kick", difficulty: "easy" },
    { word: "Goalkeeper", difficulty: "easy" },
    { word: "Striker", difficulty: "easy" },
    { word: "Midfielder", difficulty: "easy" },
    { word: "Hat-trick", difficulty: "hard" },
    { word: "Nutmeg", difficulty: "hard" },
    { word: "Tiki-taka", difficulty: "hard" },
    { word: "False nine", difficulty: "hard" },
    { word: "Sweeper", difficulty: "hard" },
    { word: "Counter-attack", difficulty: "hard" },
    { word: "Libero", difficulty: "hard" },
    { word: "Man marking", difficulty: "hard" },
    { word: "Zonal marking", difficulty: "hard" },
    { word: "Through ball", difficulty: "hard" },
    { word: "Basketball", difficulty: "easy" },
    { word: "Tennis", difficulty: "easy" },
    { word: "Baseball", difficulty: "easy" },
    { word: "Football", difficulty: "easy" },
    { word: "Swimming", difficulty: "easy" },
    { word: "Cycling", difficulty: "easy" },
    { word: "Running", difficulty: "easy" },
    { word: "Skiing", difficulty: "easy" },
    { word: "Golf", difficulty: "easy" },
    { word: "Boxing", difficulty: "easy" },
    { word: "Decathlon", difficulty: "hard" },
    { word: "Biathlon", difficulty: "hard" },
    { word: "Polo", difficulty: "hard" },
    { word: "The Olympic Games", difficulty: "hard" },
    { word: "Bobsledding", difficulty: "hard" },
    { word: "Windsurfing", difficulty: "hard" },
    { word: "Triathlon", difficulty: "hard" },
    { word: "Badminton", difficulty: "hard" },
    { word: "Fencing", difficulty: "hard" },
    { word: "Lacrosse", difficulty: "hard" },
  ],
  "Movies and TV": [
    { word: "Star Wars", difficulty: "easy" },
    { word: "The Matrix", difficulty: "easy" },
    { word: "Friends", difficulty: "easy" },
    { word: "The Simpsons", difficulty: "easy" },
    { word: "Breaking Bad", difficulty: "easy" },
    { word: "Game of Thrones", difficulty: "easy" },
    { word: "Harry Potter", difficulty: "easy" },
    { word: "The Godfather", difficulty: "easy" },
    { word: "The Avengers", difficulty: "easy" },
    { word: "Lord of the Rings", difficulty: "easy" },
    { word: "Jurassic Park", difficulty: "easy" },
    { word: "The Shawshank Redemption", difficulty: "easy" },
    { word: "Pulp Fiction", difficulty: "easy" },
    { word: "Back to the Future", difficulty: "easy" },
    { word: "Star Trek", difficulty: "easy" },
    { word: "The Office", difficulty: "easy" },
    { word: "Avatar", difficulty: "easy" },
    { word: "Titanic", difficulty: "easy" },
    { word: "Inception", difficulty: "easy" },
    { word: "Stranger Things", difficulty: "easy" },
    { word: "The Lion King", difficulty: "easy" },
    { word: "Forrest Gump", difficulty: "easy" },
    { word: "The Dark Knight", difficulty: "easy" },
    { word: "Toy Story", difficulty: "easy" },
    { word: "The Walking Dead", difficulty: "easy" },
    { word: "Frozen", difficulty: "easy" },
    { word: "The Big Bang Theory", difficulty: "easy" },
    { word: "Indiana Jones", difficulty: "easy" },
    { word: "The Sound of Music", difficulty: "easy" },
    { word: "The Sopranos", difficulty: "easy" },
    { word: "Toy Story", difficulty: "easy" },
    { word: "The Terminator", difficulty: "easy" },
    { word: "Mulan", difficulty: "easy" },
    { word: "Die Hard", difficulty: "easy" },
    { word: "The Witcher", difficulty: "easy" },
    { word: "The Hunger Games", difficulty: "easy" },
    { word: "Mad Men", difficulty: "easy" },
    { word: "The Princess Bride", difficulty: "easy" },
    { word: "Stranger Things", difficulty: "easy" },
    { word: "Mission: Impossible", difficulty: "easy" },
    { word: "The Twilight Zone", difficulty: "easy" },
    { word: "The Office", difficulty: "easy" },
    { word: "The Good Place", difficulty: "easy" },
    { word: "The X-Files", difficulty: "easy" },
    { word: "The Witcher", difficulty: "easy" },
    { word: "Avatar: The Last Airbender", difficulty: "easy" },
    { word: "The Crown", difficulty: "easy" },
    { word: "The Simpsons", difficulty: "easy" },
    { word: "The Mandalorian", difficulty: "easy" },
    { word: "Leonardo DiCaprio", difficulty: "easy" },
    { word: "Harry Potter", difficulty: "easy" },
    { word: "Star Wars", difficulty: "easy" },
    { word: "Game of Thrones", difficulty: "easy" },
    { word: "The Godfather", difficulty: "easy" },
    { word: "Actor", difficulty: "easy" },
    { word: "Director", difficulty: "easy" },
    { word: "Oscar", difficulty: "easy" },
    { word: "Red carpet", difficulty: "easy" },
    { word: "Blockbuster", difficulty: "easy" },
    { word: "Movie", difficulty: "easy" },
    { word: "Premiere", difficulty: "easy" },
    { word: "Screenwriter", difficulty: "easy" },
    { word: "Studio", difficulty: "easy" },
    { word: "Sequel", difficulty: "easy" },
    { word: "Cinematography", difficulty: "hard" },
    { word: "Method acting", difficulty: "hard" },
    { word: "Film noir", difficulty: "hard" },
    { word: "Biopic", difficulty: "hard" },
    { word: "Cameo", difficulty: "hard" },
    { word: "Auteur", difficulty: "hard" },
    { word: "Casting couch", difficulty: "hard" },
    { word: "Stunt double", difficulty: "hard" },
    { word: "Box office", difficulty: "hard" },
    { word: "Green screen", difficulty: "hard" },
    { word: "Friends", difficulty: "easy" },
    { word: "Game of Thrones", difficulty: "easy" },
    { word: "Breaking Bad", difficulty: "easy" },
    { word: "The Office", difficulty: "easy" },
    { word: "Stranger Things", difficulty: "easy" },
    { word: "Grey's Anatomy", difficulty: "easy" },
    { word: "The Simpsons", difficulty: "easy" },
    { word: "Seinfeld", difficulty: "easy" },
    { word: "The Big Bang Theory", difficulty: "easy" },
    { word: "How I Met Your Mother", difficulty: "easy" },
    { word: "Twin Peaks", difficulty: "hard" },
    { word: "Black Mirror", difficulty: "hard" },
    { word: "The Crown", difficulty: "hard" },
    { word: "True Detective", difficulty: "hard" },
    { word: "The Handmaid's Tale", difficulty: "hard" },
    { word: "Mad Men", difficulty: "hard" },
    { word: "Westworld", difficulty: "hard" },
    { word: "The Mandalorian", difficulty: "hard" },
    { word: "The Sopranos", difficulty: "hard" },
    { word: "Better Call Saul", difficulty: "hard" },
  ],
  "Food and Drink": [
    { word: "Pizza", difficulty: "easy" },
    { word: "Chocolate", difficulty: "easy" },
    { word: "Burger", difficulty: "easy" },
    { word: "Coffee", difficulty: "easy" },
    { word: "Sushi", difficulty: "easy" },
    { word: "Ice Cream", difficulty: "easy" },
    { word: "Pasta", difficulty: "easy" },
    { word: "Wine", difficulty: "easy" },
    { word: "Beer", difficulty: "easy" },
    { word: "Steak", difficulty: "easy" },
    { word: "Salad", difficulty: "easy" },
    { word: "Sandwich", difficulty: "easy" },
    { word: "Cheese", difficulty: "easy" },
    { word: "Cupcake", difficulty: "easy" },
    { word: "Tea", difficulty: "easy" },
    { word: "Cookie", difficulty: "easy" },
    { word: "Tacos", difficulty: "easy" },
    { word: "Whiskey", difficulty: "easy" },
    { word: "Bread", difficulty: "easy" },
    { word: "Cocktail", difficulty: "easy" },
    { word: "Smoothie", difficulty: "easy" },
    { word: "Donut", difficulty: "easy" },
    { word: "Soup", difficulty: "easy" },
    { word: "Cake", difficulty: "easy" },
    { word: "Barbecue", difficulty: "easy" },
    { word: "Pancakes", difficulty: "easy" },
    { word: "Ramen", difficulty: "easy" },
    { word: "Lobster", difficulty: "easy" },
    { word: "Curry", difficulty: "easy" },
    { word: "Gin", difficulty: "easy" },
    { word: "Vodka", difficulty: "easy" },
    { word: "Caviar", difficulty: "easy" },
    { word: "Macaron", difficulty: "easy" },
    { word: "Paella", difficulty: "easy" },
    { word: "Hot Dog", difficulty: "easy" },
    { word: "Dim Sum", difficulty: "easy" },
    { word: "Champagne", difficulty: "easy" },
    { word: "Margarita", difficulty: "easy" },
    { word: "Gourmet", difficulty: "easy" },
    { word: "Milkshake", difficulty: "easy" },
    { word: "Risotto", difficulty: "easy" },
    { word: "Pho", difficulty: "easy" },
    { word: "Nachos", difficulty: "easy" },
    { word: "Cider", difficulty: "easy" },
    { word: "Fondue", difficulty: "easy" },
    { word: "Poutine", difficulty: "easy" },
    { word: "Tapas", difficulty: "easy" },
    { word: "Biscuit", difficulty: "easy" },
    { word: "Pizza", difficulty: "easy" },
    { word: "Burger", difficulty: "easy" },
    { word: "Pasta", difficulty: "easy" },
    { word: "Sushi", difficulty: "easy" },
    { word: "Ice cream", difficulty: "easy" },
    { word: "Salad", difficulty: "easy" },
    { word: "Sandwich", difficulty: "easy" },
    { word: "Steak", difficulty: "easy" },
    { word: "Coffee", difficulty: "easy" },
    { word: "Tea", difficulty: "easy" },
    { word: "Eggs Benedict", difficulty: "hard" },
    { word: "Beef Wellington", difficulty: "hard" },
    { word: "Lobster Bisque", difficulty: "hard" },
    { word: "Croque Monsieur", difficulty: "hard" },
    { word: "Chicken Parmesan", difficulty: "hard" },
    { word: "Tiramisu", difficulty: "hard" },
    { word: "Coq au Vin", difficulty: "hard" },
    { word: "Crème Brûlée", difficulty: "hard" },
    { word: "Spaghetti Carbonara", difficulty: "hard" },
    { word: "Banoffee Pie", difficulty: "hard" },
  ],
  "Nature and Wildlife": [
    { word: "Elephant", difficulty: "easy" },
    { word: "Rainforest", difficulty: "easy" },
    { word: "Penguin", difficulty: "easy" },
    { word: "Mountain", difficulty: "easy" },
    { word: "Whale", difficulty: "easy" },
    { word: "Sunset", difficulty: "easy" },
    { word: "Tiger", difficulty: "easy" },
    { word: "Savannah", difficulty: "easy" },
    { word: "Coral Reef", difficulty: "easy" },
    { word: "Desert", difficulty: "easy" },
    { word: "Waterfall", difficulty: "easy" },
    { word: "Polar Bear", difficulty: "easy" },
    { word: "Orangutan", difficulty: "easy" },
    { word: "Volcano", difficulty: "easy" },
    { word: "Forest", difficulty: "easy" },
    { word: "Giraffe", difficulty: "easy" },
    { word: "Lion", difficulty: "easy" },
    { word: "Dolphin", difficulty: "easy" },
    { word: "Jungle", difficulty: "easy" },
    { word: "Arctic", difficulty: "easy" },
    { word: "Humpback Whale", difficulty: "easy" },
    { word: "Cheetah", difficulty: "easy" },
    { word: "Sunrise", difficulty: "easy" },
    { word: "Koala", difficulty: "easy" },
    { word: "Cactus", difficulty: "easy" },
    { word: "Ocean", difficulty: "easy" },
    { word: "Redwood Tree", difficulty: "easy" },
    { word: "Squirrel", difficulty: "easy" },
    { word: "Oasis", difficulty: "easy" },
    { word: "Eagle", difficulty: "easy" },
    { word: "Butterfly", difficulty: "easy" },
    { word: "Moose", difficulty: "easy" },
    { word: "Fjord", difficulty: "easy" },
    { word: "Komodo Dragon", difficulty: "easy" },
    { word: "Seal", difficulty: "easy" },
    { word: "Tropical Fish", difficulty: "easy" },
    { word: "Monsoon", difficulty: "easy" },
    { word: "Lemur", difficulty: "easy" },
    { word: "Bamboo Forest", difficulty: "easy" },
    { word: "Hummingbird", difficulty: "easy" },
    { word: "Glacier", difficulty: "easy" },
    { word: "Antarctica", difficulty: "easy" },
    { word: "Chameleon", difficulty: "easy" },
    { word: "Mangrove", difficulty: "easy" },
    { word: "Seahorse", difficulty: "easy" },
    { word: "Aurora", difficulty: "easy" },
    { word: "Octopus", difficulty: "easy" },
    { word: "Cat", difficulty: "easy" },
    { word: "Dog", difficulty: "easy" },
    { word: "Elephant", difficulty: "easy" },
    { word: "Lion", difficulty: "easy" },
    { word: "Tiger", difficulty: "easy" },
    { word: "Giraffe", difficulty: "easy" },
    { word: "Kangaroo", difficulty: "easy" },
    { word: "Penguin", difficulty: "easy" },
    { word: "Dolphin", difficulty: "easy" },
    { word: "Shark", difficulty: "easy" },
    { word: "Axolotl", difficulty: "hard" },
    { word: "Platypus", difficulty: "hard" },
    { word: "Tasmanian Devil", difficulty: "hard" },
    { word: "Electric Eel", difficulty: "hard" },
    { word: "Narwhal", difficulty: "hard" },
    { word: "Komodo Dragon", difficulty: "hard" },
    { word: "Emperor Penguin", difficulty: "hard" },
    { word: "Snow Leopard", difficulty: "hard" },
    { word: "Great White Shark", difficulty: "hard" },
    { word: "African Grey Parrot", difficulty: "hard" },
  ],
  "Languages": [
    { word: "English", difficulty: "easy" },
    { word: "Spanish", difficulty: "easy" },
    { word: "French", difficulty: "easy" },
    { word: "Mandarin", difficulty: "easy" },
    { word: "German", difficulty: "easy" },
    { word: "Italian", difficulty: "easy" },
    { word: "Japanese", difficulty: "easy" },
    { word: "Russian", difficulty: "easy" },
    { word: "Portuguese", difficulty: "easy" },
    { word: "Arabic", difficulty: "easy" },
    { word: "Korean", difficulty: "easy" },
    { word: "Dutch", difficulty: "easy" },
    { word: "Swedish", difficulty: "easy" },
    { word: "Greek", difficulty: "easy" },
    { word: "Turkish", difficulty: "easy" },
    { word: "Polish", difficulty: "easy" },
    { word: "Hindi", difficulty: "easy" },
    { word: "Thai", difficulty: "easy" },
    { word: "Finnish", difficulty: "easy" },
    { word: "Vietnamese", difficulty: "easy" },
    { word: "Indonesian", difficulty: "easy" },
    { word: "Hebrew", difficulty: "easy" },
    { word: "Czech", difficulty: "easy" },
    { word: "Hungarian", difficulty: "easy" },
    { word: "Romanian", difficulty: "easy" },
    { word: "Danish", difficulty: "easy" },
    { word: "Norwegian", difficulty: "easy" },
    { word: "Persian", difficulty: "easy" },
    { word: "Swahili", difficulty: "easy" },
    { word: "Tagalog", difficulty: "easy" },
    { word: "Malay", difficulty: "easy" },
    { word: "Bengali", difficulty: "easy" },
    { word: "Slovak", difficulty: "easy" },
    { word: "Lithuanian", difficulty: "easy" },
    { word: "Latvian", difficulty: "easy" },
    { word: "Slovenian", difficulty: "easy" },
    { word: "Croatian", difficulty: "easy" },
    { word: "Ukrainian", difficulty: "easy" },
    { word: "Estonian", difficulty: "easy" },
    { word: "Icelandic", difficulty: "easy" },
    { word: "Basque", difficulty: "easy" },
    { word: "Welsh", difficulty: "easy" },
    { word: "Farsi", difficulty: "easy" },
    { word: "Yiddish", difficulty: "easy" },
    { word: "Amharic", difficulty: "easy" },
    { word: "Zulu", difficulty: "easy" },
    { word: "Xhosa", difficulty: "easy" },
    { word: "Kurdish", difficulty: "easy" }
  ],
  "Famous Personalities": [
    { word: "Albert Einstein", difficulty: "easy" },
    { word: "Leonardo da Vinci", difficulty: "easy" },
    { word: "Nelson Mandela", difficulty: "easy" },
    { word: "William Shakespeare", difficulty: "easy" },
    { word: "Mahatma Gandhi", difficulty: "easy" },
    { word: "Mother Teresa", difficulty: "easy" },
    { word: "Martin Luther King Jr.", difficulty: "easy" },
    { word: "Marie Curie", difficulty: "easy" },
    { word: "Elvis Presley", difficulty: "easy" },
    { word: "Michael Jackson", difficulty: "easy" },
    { word: "Pablo Picasso", difficulty: "easy" },
    { word: "Cleopatra", difficulty: "easy" },
    { word: "Wolfgang Amadeus Mozart", difficulty: "easy" },
    { word: "Charles Darwin", difficulty: "easy" },
    { word: "Abraham Lincoln", difficulty: "easy" },
    { word: "Vincent van Gogh", difficulty: "easy" },
    { word: "Amelia Earhart", difficulty: "easy" },
    { word: "Steve Jobs", difficulty: "easy" },
    { word: "Stephen Hawking", difficulty: "easy" },
    { word: "Oprah Winfrey", difficulty: "easy" },
    { word: "Leonardo DiCaprio", difficulty: "easy" },
    { word: "Beethoven", difficulty: "easy" },
    { word: "Frida Kahlo", difficulty: "easy" },
    { word: "Alexander the Great", difficulty: "easy" },
    { word: "Jane Austen", difficulty: "easy" },
    { word: "Walt Disney", difficulty: "easy" },
    { word: "Muhammad Ali", difficulty: "easy" },
    { word: "Marlon Brando", difficulty: "easy" },
    { word: "Coco Chanel", difficulty: "easy" },
    { word: "Neil Armstrong", difficulty: "easy" },
    { word: "Malala Yousafzai", difficulty: "easy" },
    { word: "J.K. Rowling", difficulty: "easy" },
    { word: "David Bowie", difficulty: "easy" },
    { word: "Diana, Princess of Wales", difficulty: "easy" },
    { word: "Che Guevara", difficulty: "easy" },
    { word: "Socrates", difficulty: "easy" },
    { word: "Helen Keller", difficulty: "easy" },
    { word: "Queen Elizabeth II", difficulty: "easy" },
    { word: "Salvador Dalí", difficulty: "easy" },
    { word: "Marie Antoinette", difficulty: "easy" },
    { word: "Pele", difficulty: "easy" },
    { word: "Emily Dickinson", difficulty: "easy" },
    { word: "Napoleon Bonaparte", difficulty: "easy" },
    { word: "Beyoncé", difficulty: "easy" },
    { word: "George Orwell", difficulty: "easy" },
    { word: "Stephen Spielberg", difficulty: "easy" },
    { word: "Audrey Hepburn", difficulty: "easy" },
    { word: "Pope Francis", difficulty: "easy" },
    { word: "Brad Pitt", difficulty: "easy" },
    { word: "Angelina Jolie", difficulty: "easy" },
    { word: "Tom Cruise", difficulty: "easy" },
    { word: "Jennifer Aniston", difficulty: "easy" },
    { word: "Leonardo DiCaprio", difficulty: "easy" },
    { word: "Taylor Swift", difficulty: "easy" },
    { word: "Dwayne Johnson", difficulty: "easy" },
    { word: "Robert Downey Jr.", difficulty: "easy" },
    { word: "Scarlett Johansson", difficulty: "easy" },
    { word: "Benedict Cumberbatch", difficulty: "hard" },
    { word: "Keanu Reeves", difficulty: "hard" },
    { word: "Natalie Portman", difficulty: "hard" },
    { word: "Joaquin Phoenix", difficulty: "hard" },
    { word: "Charlize Theron", difficulty: "hard" },
    { word: "Michael Fassbender", difficulty: "hard" },
    { word: "Cate Blanchett", difficulty: "hard" },
    { word: "Tilda Swinton", difficulty: "hard" },
    { word: "Christoph Waltz", difficulty: "hard" },
    { word: "Saoirse Ronan", difficulty: "hard" }
  ],
  "Current Events": [
    { word: "COVID-19 Pandemic", difficulty: "easy" },
    { word: "Climate Change", difficulty: "easy" },
    { word: "Space Exploration", difficulty: "easy" },
    { word: "Olympic Games", difficulty: "easy" },
    { word: "Presidential Election", difficulty: "easy" },
    { word: "Global Warming", difficulty: "easy" },
    { word: "Brexit", difficulty: "easy" },
    { word: "Cybersecurity", difficulty: "easy" },
    { word: "Artificial Intelligence", difficulty: "easy" },
    { word: "Social Media", difficulty: "easy" },
    { word: "Electric Vehicles", difficulty: "easy" },
    { word: "Mars Rover Mission", difficulty: "easy" },
    { word: "Protests", difficulty: "easy" },
    { word: "Vaccination Campaigns", difficulty: "easy" },
    { word: "Trade Wars", difficulty: "easy" },
    { word: "Wildfires", difficulty: "easy" },
    { word: "Refugee Crisis", difficulty: "easy" },
    { word: "Terrorist Attacks", difficulty: "easy" },
    { word: "Space Tourism", difficulty: "easy" },
    { word: "Cryptocurrency Boom", difficulty: "easy" },
    { word: "Healthcare Reform", difficulty: "easy" },
    { word: "Artificial Meat", difficulty: "easy" },
    { word: "Pandemic Response", difficulty: "easy" },
    { word: "Environmental Policies", difficulty: "easy" },
    { word: "Gig Economy", difficulty: "easy" },
    { word: "Student Protests", difficulty: "easy" },
    { word: "Rising Inflation", difficulty: "easy" },
    { word: "Homelessness Crisis", difficulty: "easy" },
    { word: "Online Education", difficulty: "easy" },
    { word: "Political Scandals", difficulty: "easy" },
    { word: "Social Justice Movements", difficulty: "easy" },
    { word: "Space Race", difficulty: "easy" },
    { word: "Economic Stimulus Packages", difficulty: "easy" },
    { word: "AI Ethics Debate", difficulty: "easy" },
    { word: "Remote Work Trends", difficulty: "easy" },
    { word: "Ransomware Attacks", difficulty: "easy" },
    { word: "Sustainable Development Goals", difficulty: "easy" },
    { word: "Plastic Pollution", difficulty: "easy" },
    { word: "Food Security", difficulty: "easy" },
    { word: "Medical Breakthroughs", difficulty: "easy" },
    { word: "Gender Equality Movements", difficulty: "easy" },
    { word: "Social Distancing", difficulty: "easy" },
    { word: "Renewable Energy Initiatives", difficulty: "easy" },
    { word: "Remote Voting", difficulty: "easy" },
    { word: "Digital Privacy Issues", difficulty: "easy" },
    { word: "Climate Activism", difficulty: "easy" },
    { word: "Space Debris", difficulty: "easy" }
  ],
  "Religion and Mythology": [
    { word: "God", difficulty: "easy" },
    { word: "Zeus", difficulty: "easy" },
    { word: "Buddha", difficulty: "easy" },
    { word: "Jesus", difficulty: "easy" },
    { word: "Thor", difficulty: "easy" },
    { word: "Hinduism", difficulty: "easy" },
    { word: "Egyptian Mythology", difficulty: "easy" },
    { word: "Greek Mythology", difficulty: "easy" },
    { word: "Christianity", difficulty: "easy" },
    { word: "Islam", difficulty: "easy" },
    { word: "Shiva", difficulty: "easy" },
    { word: "Bible", difficulty: "easy" },
    { word: "Vishnu", difficulty: "easy" },
    { word: "Odin", difficulty: "easy" },
    { word: "Mythology", difficulty: "easy" },
    { word: "Paganism", difficulty: "easy" },
    { word: "Taoism", difficulty: "easy" },
    { word: "Myth", difficulty: "easy" },
    { word: "Ancient Greek Gods", difficulty: "easy" },
    { word: "Norse Mythology", difficulty: "easy" },
    { word: "Theology", difficulty: "easy" },
    { word: "Creation Myth", difficulty: "easy" },
    { word: "Divinity", difficulty: "easy" },
    { word: "Pantheon", difficulty: "easy" },
    { word: "Deity", difficulty: "easy" },
    { word: "Ragnarok", difficulty: "easy" },
    { word: "Monotheism", difficulty: "easy" },
    { word: "Polytheism", difficulty: "easy" },
    { word: "Hindu Gods", difficulty: "easy" },
    { word: "Greek Gods", difficulty: "easy" },
    { word: "Roman Mythology", difficulty: "easy" },
    { word: "Norse Gods", difficulty: "easy" },
    { word: "Holy", difficulty: "easy" },
    { word: "Sacred", difficulty: "easy" },
    { word: "Religious Text", difficulty: "easy" },
    { word: "Angel", difficulty: "easy" },
    { word: "Demon", difficulty: "easy" },
    { word: "Pagan Gods", difficulty: "easy" },
    { word: "Heaven", difficulty: "easy" },
    { word: "Hell", difficulty: "easy" },
    { word: "Mythical Creatures", difficulty: "easy" },
    { word: "Religion", difficulty: "easy" },
    { word: "Mythological Beings", difficulty: "easy" },
    { word: "Holy Book", difficulty: "easy" },
    { word: "Prophet", difficulty: "easy" },
    { word: "Goddess", difficulty: "easy" },
    { word: "Ancient Gods", difficulty: "easy" },
    { word: "Divine", difficulty: "easy" },
    { word: "Zeus", difficulty: "easy" },
    { word: "Hercules", difficulty: "easy" },
    { word: "Thor", difficulty: "easy" },
    { word: "Medusa", difficulty: "easy" },
    { word: "Minotaur", difficulty: "easy" },
    { word: "Poseidon", difficulty: "easy" },
    { word: "Apollo", difficulty: "easy" },
    { word: "Athena", difficulty: "easy" },
    { word: "Hades", difficulty: "easy" },
    { word: "Pandora", difficulty: "easy" },
    { word: "Ragnarok", difficulty: "hard" },
    { word: "Prometheus", difficulty: "hard" },
    { word: "Persephone", difficulty: "hard" },
    { word: "Charon", difficulty: "hard" },
    { word: "Bifrost Bridge", difficulty: "hard" },
    { word: "Valkyrie", difficulty: "hard" },
    { word: "Fenrir", difficulty: "hard" },
    { word: "Yggdrasil", difficulty: "hard" },
    { word: "Chimera", difficulty: "hard" },
    { word: "Labyrinth of Crete", difficulty: "hard" },
  ],
  "Space and Astronomy": [
    { word: "Galaxy", difficulty: "easy" },
    { word: "Black Hole", difficulty: "easy" },
    { word: "Star", difficulty: "easy" },
    { word: "Planet", difficulty: "easy" },
    { word: "Solar System", difficulty: "easy" },
    { word: "Moon", difficulty: "easy" },
    { word: "Comet", difficulty: "easy" },
    { word: "Asteroid", difficulty: "easy" },
    { word: "Constellation", difficulty: "easy" },
    { word: "Milky Way", difficulty: "easy" },
    { word: "Nebula", difficulty: "easy" },
    { word: "Space Station", difficulty: "easy" },
    { word: "Supernova", difficulty: "easy" },
    { word: "Telescope", difficulty: "easy" },
    { word: "Mars", difficulty: "easy" },
    { word: "Satellite", difficulty: "easy" },
    { word: "Exoplanet", difficulty: "easy" },
    { word: "Space Exploration", difficulty: "easy" },
    { word: "Big Bang", difficulty: "easy" },
    { word: "Cosmos", difficulty: "easy" },
    { word: "Hubble Space Telescope", difficulty: "easy" },
    { word: "Orbit", difficulty: "easy" },
    { word: "Spacecraft", difficulty: "easy" },
    { word: "Rocket", difficulty: "easy" },
    { word: "Interstellar", difficulty: "easy" },
    { word: "Gravity", difficulty: "easy" },
    { word: "Galactic", difficulty: "easy" },
    { word: "Lunar", difficulty: "easy" },
    { word: "Milky Way Galaxy", difficulty: "easy" },
    { word: "Outer Space", difficulty: "easy" },
    { word: "Astrobiology", difficulty: "easy" },
    { word: "Black Holes", difficulty: "easy" },
    { word: "Dark Matter", difficulty: "easy" },
    { word: "Planetary", difficulty: "easy" },
    { word: "Space Travel", difficulty: "easy" },
    { word: "Astrophysics", difficulty: "easy" },
    { word: "Neutron Star", difficulty: "easy" },
    { word: "Cosmology", difficulty: "easy" },
    { word: "Meteor Shower", difficulty: "easy" },
    { word: "Space Telescope", difficulty: "easy" },
    { word: "Astronaut", difficulty: "easy" },
    { word: "Solar Eclipse", difficulty: "easy" },
    { word: "Orbital", difficulty: "easy" },
    { word: "Stellar", difficulty: "easy" },
    { word: "Space Mission", difficulty: "easy" },
    { word: "Astronomy", difficulty: "easy" },
    { word: "Space Race", difficulty: "easy" },
    { word: "Earth", difficulty: "easy" },
    { word: "Moon", difficulty: "easy" },
    { word: "Sun", difficulty: "easy" },
    { word: "Mars", difficulty: "easy" },
    { word: "Stars", difficulty: "easy" },
    { word: "Galaxy", difficulty: "easy" },
    { word: "Asteroid", difficulty: "easy" },
    { word: "Comet", difficulty: "easy" },
    { word: "Meteor", difficulty: "easy" },
    { word: "Satellite", difficulty: "easy" },
    { word: "Black Hole", difficulty: "hard" },
    { word: "Supernova", difficulty: "hard" },
    { word: "Light Year", difficulty: "hard" },
    { word: "Milky Way", difficulty: "hard" },
    { word: "Red Giant", difficulty: "hard" },
    { word: "White Dwarf", difficulty: "hard" },
    { word: "Event Horizon", difficulty: "hard" },
    { word: "Dark Matter", difficulty: "hard" },
    { word: "Cosmic Microwave Background", difficulty: "hard" },
    { word: "Gravitational Waves", difficulty: "hard" },
  ],
  "Inventions and Discoveries": [
    { word: "Electricity", difficulty: "easy" },
    { word: "Telephone", difficulty: "easy" },
    { word: "Internet", difficulty: "easy" },
    { word: "Computer", difficulty: "easy" },
    { word: "Printing Press", difficulty: "easy" },
    { word: "Penicillin", difficulty: "easy" },
    { word: "Vaccination", difficulty: "easy" },
    { word: "Airplane", difficulty: "easy" },
    { word: "Radio", difficulty: "easy" },
    { word: "Television", difficulty: "easy" },
    { word: "Steam Engine", difficulty: "easy" },
    { word: "Light Bulb", difficulty: "easy" },
    { word: "Photography", difficulty: "easy" },
    { word: "Microscope", difficulty: "easy" },
    { word: "Antibiotics", difficulty: "easy" },
    { word: "Theory of Relativity", difficulty: "easy" },
    { word: "DNA Double Helix", difficulty: "easy" },
    { word: "Wheel", difficulty: "easy" },
    { word: "Satellite", difficulty: "easy" },
    { word: "Space Exploration", difficulty: "easy" },
    { word: "Robotics", difficulty: "easy" },
    { word: "Electric Light", difficulty: "easy" },
    { word: "Internet of Things", difficulty: "easy" },
    { word: "Atomic Theory", difficulty: "easy" },
    { word: "Pen", difficulty: "easy" },
    { word: "Calculator", difficulty: "easy" },
    { word: "Genetics", difficulty: "easy" },
    { word: "X-ray", difficulty: "easy" },
    { word: "Helicopter", difficulty: "easy" },
    { word: "Plastic", difficulty: "easy" },
    { word: "Submarine", difficulty: "easy" },
    { word: "Artificial Intelligence", difficulty: "easy" },
    { word: "Fiber Optics", difficulty: "easy" },
    { word: "Refrigerator", difficulty: "easy" },
    { word: "Laser", difficulty: "easy" },
    { word: "Printing", difficulty: "easy" },
    { word: "Photovoltaic Cell", difficulty: "easy" },
    { word: "Nuclear Power", difficulty: "easy" },
    { word: "Electric Motor", difficulty: "easy" },
    { word: "Semiconductor", difficulty: "easy" },
    { word: "Satnav", difficulty: "easy" },
    { word: "Artificial Heart", difficulty: "easy" },
    { word: "Internet Protocol (IP)", difficulty: "easy" },
    { word: "Neutron Bomb", difficulty: "easy" },
    { word: "MRI", difficulty: "easy" },
    { word: "Quantum Theory", difficulty: "easy" },
    { word: "Nanotechnology", difficulty: "easy" },
    { word: "Telephone", difficulty: "easy" },
    { word: "Light bulb", difficulty: "easy" },
    { word: "Airplane", difficulty: "easy" },
    { word: "Car", difficulty: "easy" },
    { word: "Television", difficulty: "easy" },
    { word: "Computer", difficulty: "easy" },
    { word: "Radio", difficulty: "easy" },
    { word: "Camera", difficulty: "easy" },
    { word: "Printing Press", difficulty: "easy" },
    { word: "Microwave", difficulty: "easy" },
    { word: "Steam Engine", difficulty: "hard" },
    { word: "Penicillin", difficulty: "hard" },
    { word: "Electric Motor", difficulty: "hard" },
    { word: "Thermometer", difficulty: "hard" },
    { word: "Stethoscope", difficulty: "hard" },
    { word: "Typewriter", difficulty: "hard" },
    { word: "Sewing Machine", difficulty: "hard" },
    { word: "Solar Panel", difficulty: "hard" },
    { word: "Barcode", difficulty: "hard" },
    { word: "Transistor", difficulty: "hard" },
  ],
  "Health and Medicine": [
    { word: "Heart", difficulty: "easy" },
    { word: "Brain", difficulty: "easy" },
    { word: "Lungs", difficulty: "easy" },
    { word: "Bones", difficulty: "easy" },
    { word: "Blood", difficulty: "easy" },
    { word: "DNA", difficulty: "easy" },
    { word: "Virus", difficulty: "easy" },
    { word: "Bacteria", difficulty: "easy" },
    { word: "Antibiotics", difficulty: "easy" },
    { word: "Vaccination", difficulty: "easy" },
    { word: "Cancer", difficulty: "easy" },
    { word: "Diabetes", difficulty: "easy" },
    { word: "Obesity", difficulty: "easy" },
    { word: "Immune System", difficulty: "easy" },
    { word: "Surgery", difficulty: "easy" },
    { word: "Anatomy", difficulty: "easy" },
    { word: "Physiology", difficulty: "easy" },
    { word: "Mental Health", difficulty: "easy" },
    { word: "Pandemic", difficulty: "easy" },
    { word: "Healthcare", difficulty: "easy" },
    { word: "Genetics", difficulty: "easy" },
    { word: "Stethoscope", difficulty: "easy" },
    { word: "X-ray", difficulty: "easy" },
    { word: "MRI", difficulty: "easy" },
    { word: "Emergency Room", difficulty: "easy" },
    { word: "Pharmacy", difficulty: "easy" },
    { word: "Medical Research", difficulty: "easy" },
    { word: "Epidemic", difficulty: "easy" },
    { word: "Public Health", difficulty: "easy" },
    { word: "Pulse", difficulty: "easy" },
    { word: "Fever", difficulty: "easy" },
    { word: "Hygiene", difficulty: "easy" },
    { word: "Cholesterol", difficulty: "easy" },
    { word: "Allergies", difficulty: "easy" },
    { word: "Depression", difficulty: "easy" },
    { word: "Pain", difficulty: "easy" },
    { word: "Physical Therapy", difficulty: "easy" },
    { word: "Health Insurance", difficulty: "easy" },
    { word: "Hospice Care", difficulty: "easy" },
    { word: "Medical Ethics", difficulty: "easy" },
    { word: "Nutrition", difficulty: "easy" },
    { word: "Exercise", difficulty: "easy" },
    { word: "Disease", difficulty: "easy" },
    { word: "First Aid", difficulty: "easy" },
    { word: "Therapy", difficulty: "easy" },
    { word: "Epidemiology", difficulty: "easy" },
    { word: "Anesthesia", difficulty: "easy" }
  ],
  "Games and Toys": [
    { word: "Chess", difficulty: "easy" },
    { word: "Monopoly", difficulty: "easy" },
    { word: "LEGO", difficulty: "easy" },
    { word: "Puzzle", difficulty: "easy" },
    { word: "Dolls", difficulty: "easy" },
    { word: "Video Games", difficulty: "easy" },
    { word: "Board Game", difficulty: "easy" },
    { word: "Action Figures", difficulty: "easy" },
    { word: "Rubik's Cube", difficulty: "easy" },
    { word: "Card Game", difficulty: "easy" },
    { word: "Toy Cars", difficulty: "easy" },
    { word: "Dungeons & Dragons", difficulty: "easy" },
    { word: "Lego Bricks", difficulty: "easy" },
    { word: "Barbie", difficulty: "easy" },
    { word: "Teddy Bear", difficulty: "easy" },
    { word: "Nintendo", difficulty: "easy" },
    { word: "PlayStation", difficulty: "easy" },
    { word: "Xbox", difficulty: "easy" },
    { word: "Dungeons and Dragons", difficulty: "easy" },
    { word: "Checkers", difficulty: "easy" },
    { word: "Jigsaw Puzzle", difficulty: "easy" },
    { word: "Yo-Yo", difficulty: "easy" },
    { word: "Trivial Pursuit", difficulty: "easy" },
    { word: "Hot Wheels", difficulty: "easy" },
    { word: "Transformer Toys", difficulty: "easy" },
    { word: "Barbie Dolls", difficulty: "easy" },
    { word: "Nintendo Switch", difficulty: "easy" },
    { word: "Play-Doh", difficulty: "easy" },
    { word: "Fidget Spinner", difficulty: "easy" },
    { word: "Legos", difficulty: "easy" },
    { word: "Remote Control Cars", difficulty: "easy" },
    { word: "Rubik's Cubes", difficulty: "easy" },
    { word: "Magic: The Gathering", difficulty: "easy" },
    { word: "Candy Land", difficulty: "easy" },
    { word: "G.I. Joe", difficulty: "easy" },
    { word: "Tamagotchi", difficulty: "easy" },
    { word: "Nerf Guns", difficulty: "easy" },
    { word: "Lincoln Logs", difficulty: "easy" },
    { word: "Dollhouse", difficulty: "easy" },
    { word: "Marbles", difficulty: "easy" },
    { word: "Sudoku", difficulty: "easy" },
    { word: "Toy Story", difficulty: "easy" },
    { word: "Polly Pocket", difficulty: "easy" },
    { word: "Furby", difficulty: "easy" },
    { word: "Barbie Doll", difficulty: "easy" },
    { word: "Remote Control Car", difficulty: "easy" },
    { word: "Stuffed Animals", difficulty: "easy" },
    { word: "Matchbox Cars", difficulty: "easy" }
  ],
  "Books and Authors": [
    { word: "Harry Potter", difficulty: "easy" },
    { word: "William Shakespeare", difficulty: "easy" },
    { word: "Jane Austen", difficulty: "easy" },
    { word: "George Orwell", difficulty: "easy" },
    { word: "J.K. Rowling", difficulty: "easy" },
    { word: "Charles Dickens", difficulty: "easy" },
    { word: "Mark Twain", difficulty: "easy" },
    { word: "Agatha Christie", difficulty: "easy" },
    { word: "Stephen King", difficulty: "easy" },
    { word: "The Great Gatsby", difficulty: "easy" },
    { word: "The Lord of the Rings", difficulty: "easy" },
    { word: "To Kill a Mockingbird", difficulty: "easy" },
    { word: "The Catcher in the Rye", difficulty: "easy" },
    { word: "Alice's Adventures in Wonderland", difficulty: "easy" },
    { word: "The Bible", difficulty: "easy" },
    { word: "The Hunger Games", difficulty: "easy" },
    { word: "A Song of Ice and Fire", difficulty: "easy" },
    { word: "The Odyssey", difficulty: "easy" },
    { word: "The Hobbit", difficulty: "easy" },
    { word: "Lord of the Flies", difficulty: "easy" },
    { word: "Pride and Prejudice", difficulty: "easy" },
    { word: "The Chronicles of Narnia", difficulty: "easy" },
    { word: "Moby-Dick", difficulty: "easy" },
    { word: "1984", difficulty: "easy" },
    { word: "Brave New World", difficulty: "easy" },
    { word: "The Adventures of Huckleberry Finn", difficulty: "easy" },
    { word: "Wuthering Heights", difficulty: "easy" },
    { word: "The Grapes of Wrath", difficulty: "easy" },
    { word: "Frankenstein", difficulty: "easy" },
    { word: "Little Women", difficulty: "easy" },
    { word: "Gone with the Wind", difficulty: "easy" },
    { word: "The Count of Monte Cristo", difficulty: "easy" },
    { word: "The Picture of Dorian Gray", difficulty: "easy" },
    { word: "Dracula", difficulty: "easy" },
    { word: "One Hundred Years of Solitude", difficulty: "easy" },
    { word: "The Kite Runner", difficulty: "easy" },
    { word: "The Girl with the Dragon Tattoo", difficulty: "easy" },
    { word: "The Alchemist", difficulty: "easy" },
    { word: "The Hitchhiker's Guide to the Galaxy", difficulty: "easy" },
    { word: "The Handmaid's Tale", difficulty: "easy" },
    { word: "The Book Thief", difficulty: "easy" },
    { word: "War and Peace", difficulty: "easy" },
    { word: "Les Misérables", difficulty: "easy" },
    { word: "The Shining", difficulty: "easy" },
    { word: "The Secret Garden", difficulty: "easy" },
    { word: "The Silmarillion", difficulty: "easy" },
    { word: "Anna Karenina", difficulty: "easy" },
    { word: "The Fault in Our Stars", difficulty: "easy" },
    { word: "The Road", difficulty: "easy" },
    { word: "Harry Potter", difficulty: "easy" },
    { word: "The Great Gatsby", difficulty: "easy" },
    { word: "To Kill a Mockingbird", difficulty: "easy" },
    { word: "1984", difficulty: "easy" },
    { word: "The Hobbit", difficulty: "easy" },
    { word: "Pride and Prejudice", difficulty: "easy" },
    { word: "Moby Dick", difficulty: "easy" },
    { word: "The Catcher in the Rye", difficulty: "easy" },
    { word: "The Da Vinci Code", difficulty: "easy" },
    { word: "Lord of the Rings", difficulty: "easy" },
    { word: "War and Peace", difficulty: "hard" },
    { word: "Crime and Punishment", difficulty: "hard" },
    { word: "One Hundred Years of Solitude", difficulty: "hard" },
    { word: "The Brothers Karamazov", difficulty: "hard" },
    { word: "The Grapes of Wrath", difficulty: "hard" },
    { word: "Love in the Time of Cholera", difficulty: "hard" },
    { word: "A Tale of Two Cities", difficulty: "hard" },
    { word: "The Picture of Dorian Gray", difficulty: "hard" },
    { word: "Midnight's Children", difficulty: "hard" },
    { word: "Infinite Jest", difficulty: "hard" }
  ],
  "Video Games": [
    { word: "Mario", difficulty: "easy" },
    { word: "Pac-Man", difficulty: "easy" },
    { word: "Fortnite", difficulty: "easy" },
    { word: "The Legend of Zelda", difficulty: "easy" },
    { word: "Minecraft", difficulty: "easy" },
    { word: "Pokemon", difficulty: "easy" },
    { word: "Tetris", difficulty: "easy" },
    { word: "Super Mario Bros.", difficulty: "easy" },
    { word: "Call of Duty", difficulty: "easy" },
    { word: "Overwatch", difficulty: "easy" },
    { word: "World of Warcraft", difficulty: "easy" },
    { word: "FIFA", difficulty: "easy" },
    { word: "League of Legends", difficulty: "easy" },
    { word: "Grand Theft Auto", difficulty: "easy" },
    { word: "Counter-Strike", difficulty: "easy" },
    { word: "Sonic the Hedgehog", difficulty: "easy" },
    { word: "Final Fantasy", difficulty: "easy" },
    { word: "Street Fighter", difficulty: "easy" },
    { word: "Halo", difficulty: "easy" },
    { word: "Doom", difficulty: "easy" },
    { word: "Assassin's Creed", difficulty: "easy" },
    { word: "Mortal Kombat", difficulty: "easy" },
    { word: "The Sims", difficulty: "easy" },
    { word: "StarCraft", difficulty: "easy" },
    { word: "Fortnite Battle Royale", difficulty: "easy" },
    { word: "Half-Life", difficulty: "easy" },
    { word: "Gears of War", difficulty: "easy" },
    { word: "Portal", difficulty: "easy" },
    { word: "Red Dead Redemption", difficulty: "easy" },
    { word: "Civilization", difficulty: "easy" },
    { word: "The Witcher", difficulty: "easy" },
    { word: "Super Smash Bros.", difficulty: "easy" },
    { word: "Star Wars Battlefront", difficulty: "easy" },
    { word: "PUBG (PlayerUnknown's Battlegrounds)", difficulty: "easy" },
    { word: "Mass Effect", difficulty: "easy" },
    { word: "Bioshock", difficulty: "easy" },
    { word: "God of War", difficulty: "easy" },
    { word: "Rocket League", difficulty: "easy" },
    { word: "World of Tanks", difficulty: "easy" },
    { word: "Fortnite Save the World", difficulty: "easy" },
    { word: "Destiny", difficulty: "easy" },
    { word: "Warframe", difficulty: "easy" },
    { word: "Fortnite Battle Royale", difficulty: "easy" },
    { word: "Cyberpunk 2077", difficulty: "easy" },
    { word: "Candy Crush Saga", difficulty: "easy" },
    { word: "Far Cry", difficulty: "easy" },
    { word: "Animal Crossing", difficulty: "easy" },
    { word: "Borderlands", difficulty: "easy" },
    { word: "Mario", difficulty: "easy" },
    { word: "Zelda", difficulty: "easy" },
    { word: "Sonic", difficulty: "easy" },
    { word: "Tetris", difficulty: "easy" },
    { word: "Minecraft", difficulty: "easy" },
    { word: "Fortnite", difficulty: "easy" },
    { word: "Call of Duty", difficulty: "easy" },
    { word: "Pac-Man", difficulty: "easy" },
    { word: "Pokémon", difficulty: "easy" },
    { word: "Halo", difficulty: "easy" },
    { word: "Red Dead Redemption", difficulty: "hard" },
    { word: "Dark Souls", difficulty: "hard" },
    { word: "The Witcher", difficulty: "hard" },
    { word: "Bioshock", difficulty: "hard" },
    { word: "Half-Life", difficulty: "hard" },
    { word: "Mass Effect", difficulty: "hard" },
    { word: "Portal", difficulty: "hard" },
    { word: "Deus Ex", difficulty: "hard" },
    { word: "Stardew Valley", difficulty: "hard" },
    { word: "The Last of Us", difficulty: "hard" },
  ],
  "Cars": [
    { word: "Sedan", difficulty: "easy" },
    { word: "Convertible", difficulty: "easy" },
    { word: "SUV", difficulty: "easy" },
    { word: "Coupe", difficulty: "easy" },
    { word: "Hatchback", difficulty: "easy" },
    { word: "Engine", difficulty: "easy" },
    { word: "Transmission", difficulty: "easy" },
    { word: "Headlights", difficulty: "easy" },
    { word: "Wheels", difficulty: "easy" },
    { word: "Steering wheel", difficulty: "easy" },
    { word: "Differential", difficulty: "hard" },
    { word: "Carburetor", difficulty: "hard" },
    { word: "Catalytic converter", difficulty: "hard" },
    { word: "Torque", difficulty: "hard" },
    { word: "RPM", difficulty: "hard" },
    { word: "Drivetrain", difficulty: "hard" },
    { word: "Suspension", difficulty: "hard" },
    { word: "Chassis", difficulty: "hard" },
    { word: "Fuel injection", difficulty: "hard" },
    { word: "Turbocharger", difficulty: "hard" }
  ],
  "Fashion": [
    { word: "Dress", difficulty: "easy" },
    { word: "Jeans", difficulty: "easy" },
    { word: "T-shirt", difficulty: "easy" },
    { word: "Sneakers", difficulty: "easy" },
    { word: "Jacket", difficulty: "easy" },
    { word: "Hat", difficulty: "easy" },
    { word: "Sunglasses", difficulty: "easy" },
    { word: "Scarf", difficulty: "easy" },
    { word: "Skirt", difficulty: "easy" },
    { word: "Suit", difficulty: "easy" },
    { word: "Haute Couture", difficulty: "hard" },
    { word: "Little Black Dress", difficulty: "hard" },
    { word: "Power Suit", difficulty: "hard" },
    { word: "Trench Coat", difficulty: "hard" },
    { word: "Catwalk", difficulty: "hard" },
    { word: "Fashion Week", difficulty: "hard" },
    { word: "Street Style", difficulty: "hard" },
    { word: "Capsule Wardrobe", difficulty: "hard" },
    { word: "Vintage Clothing", difficulty: "hard" },
    { word: "Sustainable Fashion", difficulty: "hard" }
  ],
};

const themes = {
  "Wedding Fever": [
    { word: "Bride", difficulty: "easy" },
    { word: "Groom", difficulty: "easy" },
    { word: "Wedding Cake", difficulty: "easy" },
    { word: "Bouquet", difficulty: "easy" },
    { word: "Honeymoon", difficulty: "easy" },
    { word: "Vows", difficulty: "easy" },
    { word: "Best Man", difficulty: "easy" },
    { word: "Maid of Honor", difficulty: "easy" },
    { word: "Wedding Ring", difficulty: "easy" },
    { word: "Reception", difficulty: "easy" },
    { word: "First Dance", difficulty: "hard" },
    { word: "Wedding Bells", difficulty: "hard" },
    { word: "Unity Candle", difficulty: "hard" },
    { word: "Wedding Planner", difficulty: "hard" },
    { word: "Flower Girl", difficulty: "hard" },
    { word: "Ring Bearer", difficulty: "hard" },
    { word: "Tuxedo", difficulty: "hard" },
    { word: "Wedding March", difficulty: "hard" },
    { word: "Bridal Shower", difficulty: "hard" },
    { word: "Bachelor Party", difficulty: "hard" }
  ],
  "Holiday Time": [
    { word: "Christmas tree", difficulty: "easy" },
    { word: "Santa Claus", difficulty: "easy" },
    { word: "Snowman", difficulty: "easy" },
    { word: "Gifts", difficulty: "easy" },
    { word: "Stockings", difficulty: "easy" },
    { word: "Reindeer", difficulty: "easy" },
    { word: "Sleigh", difficulty: "easy" },
    { word: "Caroling", difficulty: "easy" },
    { word: "Fireplace", difficulty: "easy" },
    { word: "Gingerbread", difficulty: "easy" },
    { word: "Ornament", difficulty: "easy" },
    { word: "Mistletoe", difficulty: "easy" },
    { word: "Eggnog", difficulty: "easy" },
    { word: "New Year's Eve", difficulty: "easy" },
    { word: "Hanukkah", difficulty: "easy" },
    { word: "Advent calendar", difficulty: "hard" },
    { word: "Kwanzaa", difficulty: "hard" },
    { word: "Yule log", difficulty: "hard" },
    { word: "Boxing Day", difficulty: "hard" },
    { word: "Epiphany", difficulty: "hard" },
    { word: "Menorah", difficulty: "hard" },
    { word: "Dreidel", difficulty: "hard" },
    { word: "Tinsel", difficulty: "hard" },
    { word: "Wassail", difficulty: "hard" },
    { word: "Nutcracker", difficulty: "hard" },
    { word: "Krampus", difficulty: "hard" },
    { word: "Solstice", difficulty: "hard" },
    { word: "Hogmanay", difficulty: "hard" },
    { word: "Black Friday", difficulty: "hard" },
    { word: "Feast of Seven Fishes", difficulty: "hard" }
  ],
  "Sports Event": [
    { word: "Olympic Games", difficulty: "easy" },
    { word: "World Cup", difficulty: "easy" },
    { word: "Super Bowl", difficulty: "easy" },
    { word: "Wimbledon", difficulty: "easy" },
    { word: "Tour de France", difficulty: "easy" },
    { word: "NBA Finals", difficulty: "easy" },
    { word: "Stanley Cup", difficulty: "easy" },
    { word: "Masters Tournament", difficulty: "easy" },
    { word: "Ryder Cup", difficulty: "easy" },
    { word: "Kentucky Derby", difficulty: "easy" },
    { word: "F1 Grand Prix", difficulty: "easy" },
    { word: "Rugby World Cup", difficulty: "easy" },
    { word: "MLB World Series", difficulty: "easy" },
    { word: "UFC Championship", difficulty: "easy" },
    { word: "Cricket World Cup", difficulty: "easy" },
    { word: "Heisman Trophy", difficulty: "hard" },
    { word: "The Ashes Series", difficulty: "hard" },
    { word: "UEFA Champions League", difficulty: "hard" },
    { word: "Copa America", difficulty: "hard" },
    { word: "La Liga Championship", difficulty: "hard" },
    { word: "Indy 500", difficulty: "hard" },
    { word: "PGA Championship", difficulty: "hard" },
    { word: "MotoGP", difficulty: "hard" },
    { word: "Commonwealth Games", difficulty: "hard" },
    { word: "Davis Cup", difficulty: "hard" },
    { word: "America's Cup", difficulty: "hard" },
    { word: "FA Cup Final", difficulty: "hard" },
    { word: "Six Nations Championship", difficulty: "hard" },
    { word: "Belmont Stakes", difficulty: "hard" }
  ],
  "Summer Vacation": [
    { word: "Beach", difficulty: "easy" },
    { word: "Surfing", difficulty: "easy" },
    { word: "Ice cream", difficulty: "easy" },
    { word: "Sandcastle", difficulty: "easy" },
    { word: "Sunbathing", difficulty: "easy" },
    { word: "Pool party", difficulty: "easy" },
    { word: "Barbecue", difficulty: "easy" },
    { word: "Camping", difficulty: "easy" },
    { word: "Hiking", difficulty: "easy" },
    { word: "Road trip", difficulty: "easy" },
    { word: "Water park", difficulty: "easy" },
    { word: "Fishing", difficulty: "easy" },
    { word: "Snorkeling", difficulty: "easy" },
    { word: "Jet skiing", difficulty: "easy" },
    { word: "Amusement park", difficulty: "easy" },
    { word: "Bonfire Night", difficulty: "hard" },
    { word: "Island Hopping", difficulty: "hard" },
    { word: "Deep-sea Fishing", difficulty: "hard" },
    { word: "Scenic Route", difficulty: "hard" },
    { word: "Guided Tour", difficulty: "hard" },
    { word: "Outdoor Concert", difficulty: "hard" },
    { word: "Nature Trail", difficulty: "hard" },
    { word: "Paddle Boarding", difficulty: "hard" },
    { word: "Paragliding", difficulty: "hard" },
    { word: "Cliff Diving", difficulty: "hard" },
    { word: "Kayaking", difficulty: "hard" },
    { word: "Wildlife Safari", difficulty: "hard" },
    { word: "Scuba Diving", difficulty: "hard" },
    { word: "Mountain Biking", difficulty: "hard" },
    { word: "Hot Air Balloon Ride", difficulty: "hard" }
  ],
  "Halloween Party": [
    { word: "Pumpkin", difficulty: "easy" },
    { word: "Ghost", difficulty: "easy" },
    { word: "Witch", difficulty: "easy" },
    { word: "Costume", difficulty: "easy" },
    { word: "Candy", difficulty: "easy" },
    { word: "Jack-o'-lantern", difficulty: "easy" },
    { word: "Haunted house", difficulty: "easy" },
    { word: "Skeleton", difficulty: "easy" },
    { word: "Vampire", difficulty: "easy" },
    { word: "Zombie", difficulty: "easy" },
    { word: "Trick-or-treat", difficulty: "easy" },
    { word: "Black cat", difficulty: "easy" },
    { word: "Spider web", difficulty: "easy" },
    { word: "Bat", difficulty: "easy" },
    { word: "Mask", difficulty: "easy" },
    { word: "Frankenstein's Monster", difficulty: "hard" },
    { word: "Dracula's Castle", difficulty: "hard" },
    { word: "Witch's Brew", difficulty: "hard" },
    { word: "Spooky Stories", difficulty: "hard" },
    { word: "Full Moon Night", difficulty: "hard" },
    { word: "Graveyard Shift", difficulty: "hard" },
    { word: "Poltergeist", difficulty: "hard" },
    { word: "Werewolf Transformation", difficulty: "hard" },
    { word: "Creepy Crawlies", difficulty: "hard" },
    { word: "Phantom of the Opera", difficulty: "hard" },
    { word: "Haunted Forest", difficulty: "hard" },
    { word: "Sleepy Hollow", difficulty: "hard" },
    { word: "Blood Moon", difficulty: "hard" },
    { word: "Scarecrow", difficulty: "hard" },
    { word: "Halloween Parade", difficulty: "hard" }
  ],
  "Christmas Celebration": [
    { word: "Santa Claus", difficulty: "easy" },
    { word: "Christmas tree", difficulty: "easy" },
    { word: "Snowman", difficulty: "easy" },
    { word: "Gifts", difficulty: "easy" },
    { word: "Stockings", difficulty: "easy" },
    { word: "Reindeer", difficulty: "easy" },
    { word: "Sleigh", difficulty: "easy" },
    { word: "Caroling", difficulty: "easy" },
    { word: "Fireplace", difficulty: "easy" },
    { word: "Gingerbread", difficulty: "easy" },
    { word: "Ornament", difficulty: "easy" },
    { word: "Mistletoe", difficulty: "easy" },
    { word: "Eggnog", difficulty: "easy" },
    { word: "New Year's Eve", difficulty: "easy" },
    { word: "Hanukkah", difficulty: "easy" },
    { word: "Advent Calendar", difficulty: "hard" },
    { word: "Kwanzaa", difficulty: "hard" },
    { word: "Yule Log", difficulty: "hard" },
    { word: "Boxing Day", difficulty: "hard" },
    { word: "Epiphany", difficulty: "hard" },
    { word: "Menorah", difficulty: "hard" },
    { word: "Dreidel", difficulty: "hard" },
    { word: "Tinsel", difficulty: "hard" },
    { word: "Wassail", difficulty: "hard" },
    { word: "Nutcracker", difficulty: "hard" },
    { word: "Krampus", difficulty: "hard" },
    { word: "Solstice", difficulty: "hard" },
    { word: "Hogmanay", difficulty: "hard" },
    { word: "Black Friday", difficulty: "hard" },
    { word: "Feast of Seven Fishes", difficulty: "hard" }
  ],
  "Back to School": [
    { word: "Homework", difficulty: "easy" },
    { word: "Backpack", difficulty: "easy" },
    { word: "Teacher", difficulty: "easy" },
    { word: "Classroom", difficulty: "easy" },
    { word: "Desk", difficulty: "easy" },
    { word: "Notebook", difficulty: "easy" },
    { word: "Pencil", difficulty: "easy" },
    { word: "Textbook", difficulty: "easy" },
    { word: "Lunchbox", difficulty: "easy" },
    { word: "Bus", difficulty: "easy" },
    { word: "Recess", difficulty: "easy" },
    { word: "Blackboard", difficulty: "easy" },
    { word: "Calculator", difficulty: "easy" },
    { word: "Ruler", difficulty: "easy" },
    { word: "School Bell", difficulty: "easy" },
    { word: "Parent-Teacher Conference", difficulty: "hard" },
    { word: "Science Fair Project", difficulty: "hard" },
    { word: "Field Trip", difficulty: "hard" },
    { word: "Honor Roll", difficulty: "hard" },
    { word: "Extracurricular Activities", difficulty: "hard" },
    { word: "Locker Combination", difficulty: "hard" },
    { word: "Study Group", difficulty: "hard" },
    { word: "Class President", difficulty: "hard" },
    { word: "Graduation Ceremony", difficulty: "hard" },
    { word: "Debate Club", difficulty: "hard" },
    { word: "School Assembly", difficulty: "hard" },
    { word: "Art Class", difficulty: "hard" },
    { word: "Gymnasium", difficulty: "hard" },
    { word: "History Lesson", difficulty: "hard" },
    { word: "Report Card", difficulty: "hard" }
  ],
  "Music Festival": [
    { word: "Stage", difficulty: "easy" },
    { word: "Band", difficulty: "easy" },
    { word: "Audience", difficulty: "easy" },
    { word: "Microphone", difficulty: "easy" },
    { word: "Guitar", difficulty: "easy" },
    { word: "Drums", difficulty: "easy" },
    { word: "DJ", difficulty: "easy" },
    { word: "Dance", difficulty: "easy" },
    { word: "Lights", difficulty: "easy" },
    { word: "Ticket", difficulty: "easy" },
    { word: "Camping", difficulty: "easy" },
    { word: "Tent", difficulty: "easy" },
    { word: "Soundcheck", difficulty: "easy" },
    { word: "Setlist", difficulty: "easy" },
    { word: "Encore", difficulty: "easy" },
    { word: "Backstage Pass", difficulty: "hard" },
    { word: "Crowd Surfing", difficulty: "hard" },
    { word: "Headliner", difficulty: "hard" },
    { word: "Festival Wristband", difficulty: "hard" },
    { word: "VIP Area", difficulty: "hard" },
    { word: "Acoustic Set", difficulty: "hard" },
    { word: "Merchandise Stand", difficulty: "hard" },
    { word: "Mosh Pit", difficulty: "hard" },
    { word: "Opening Act", difficulty: "hard" },
    { word: "Roadies", difficulty: "hard" },
    { word: "Tour Bus", difficulty: "hard" },
    { word: "Sound Engineer", difficulty: "hard" },
    { word: "Festival Grounds", difficulty: "hard" },
    { word: "Food Truck", difficulty: "hard" },
    { word: "Festival Vibes", difficulty: "hard" }
  ],
  "Movie Night": [
    { word: "Popcorn", difficulty: "easy" },
    { word: "Movie", difficulty: "easy" },
    { word: "Ticket", difficulty: "easy" },
    { word: "Director", difficulty: "easy" },
    { word: "Actor", difficulty: "easy" },
    { word: "Theater", difficulty: "easy" },
    { word: "Screen", difficulty: "easy" },
    { word: "Trailer", difficulty: "easy" },
    { word: "Snack", difficulty: "easy" },
    { word: "Seat", difficulty: "easy" },
    { word: "Projector", difficulty: "easy" },
    { word: "Credits", difficulty: "easy" },
    { word: "Scene", difficulty: "easy" },
    { word: "Genre", difficulty: "easy" },
    { word: "Plot", difficulty: "easy" },
    { word: "Cinematic Experience", difficulty: "hard" },
    { word: "Red Carpet Event", difficulty: "hard" },
    { word: "Independent Film", difficulty: "hard" },
    { word: "Blockbuster Hit", difficulty: "hard" },
    { word: "Special Effects", difficulty: "hard" },
    { word: "Box Office", difficulty: "hard" },
    { word: "Movie Marathon", difficulty: "hard" },
    { word: "Midnight Screening", difficulty: "hard" },
    { word: "Dolby Surround Sound", difficulty: "hard" },
    { word: "Film Festival", difficulty: "hard" },
    { word: "Cult Classic", difficulty: "hard" },
    { word: "Behind the Scenes", difficulty: "hard" },
    { word: "Movie Franchise", difficulty: "hard" },
    { word: "Character Development", difficulty: "hard" },
    { word: "Post-Credit Scene", difficulty: "hard" }
  ],
  "Adventure Trip": [
    { word: "Hiking", difficulty: "easy" },
    { word: "Backpacking", difficulty: "easy" },
    { word: "Camping", difficulty: "easy" },
    { word: "Rafting", difficulty: "easy" },
    { word: "Climbing", difficulty: "easy" },
    { word: "Road Trip", difficulty: "easy" },
    { word: "Jungle", difficulty: "easy" },
    { word: "Mountain", difficulty: "easy" },
    { word: "River", difficulty: "easy" },
    { word: "Desert", difficulty: "easy" },
    { word: "Beach", difficulty: "easy" },
    { word: "Waterfall", difficulty: "easy" },
    { word: "Wildlife", difficulty: "easy" },
    { word: "Campfire", difficulty: "easy" },
    { word: "Trail", difficulty: "easy" },
    { word: "Expedition", difficulty: "hard" },
    { word: "Survival Skills", difficulty: "hard" },
    { word: "Orienteering", difficulty: "hard" },
    { word: "Rock Climbing", difficulty: "hard" },
    { word: "Glacier Hiking", difficulty: "hard" },
    { word: "Desert Safari", difficulty: "hard" },
    { word: "River Rafting", difficulty: "hard" },
    { word: "Forest Trekking", difficulty: "hard" },
    { word: "Mountain Biking", difficulty: "hard" },
    { word: "Cave Exploration", difficulty: "hard" },
    { word: "Coastal Walk", difficulty: "hard" },
    { word: "Off-Road Adventure", difficulty: "hard" },
    { word: "High-Altitude Climb", difficulty: "hard" },
    { word: "Scuba Diving", difficulty: "hard" },
    { word: "Paragliding", difficulty: "hard" }
  ]
  // Add other themes with their words and difficulties here
};
